### ISSUE TITLE
Any trouble in use Aid Learning FrameWork can report here!

### ISSUE THREAD

**Issue by aidlearning** [aidlearning/AidLearning-FrameWork#1]

**Comment by 2151330** [comment]
I downloaded the v0.75, why can't I import the torch?
![image](https://user-images.githubusercontent.com/41284417/62355255-38165480-b541-11e9-862c-27ee46f8939a.png)

**Comment by aidlearning** [comment]
v0.75 is a mini version ,already build in python2/python3 surpport.and also built in OpenCV for python2 and 3. but the AI framework like caffe/mxnet/tensorflow/torch not built in.but when you finished the install .you can install them by hit the icon of upgrade on the destop.

![upgrade](https://user-images.githubusercontent.com/49776013/61633527-e01a5b00-acc1-11e9-9efd-87cbd33bf82f.png)

**Comment by 2151330** [comment]
So,thank you.

**Comment by 2151330** [comment]
I opened my own project .py file in Aid_code, and when I clicked run, it just prompted load success, where should I check the results

**Comment by 2151330** [comment]
I found the result in the show log, but there was a problem.
 How to import the easydict module?

**Comment by qfmail** [comment]
you can use pip install easydict to install the packet



---Original---

**Comment by 2151330** [comment]
When I use  pip install easydict, the results appear as follows:
root@localhost:/home# pip install easydict
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 6, in <module>
    from pip._internal import main
ImportError: No module named _internal

**Comment by qidiso** [comment]
you can use pip2 install easydict for python2 or pip3 install easydict for python3

**Comment by 2151330** [comment]
@qidiso Wow !It works,thank you very much.

**Comment by 2151330** [comment]
我在运行自己的代码时，出现了这个问题，上网查阅后，错误原因是python在linux下使用多进程遇到3770问题，在安装python时没有挂载/dev/shm 或者 对于 /dev/shm没有写的权限，此时在安装python时不能够开启 sem_open。请问我应该如何解决，可以卸载python重新安装吗
![image](https://user-images.githubusercontent.com/41284417/62445234-56bf5a00-b792-11e9-9c05-75159df174ab.png)

**Comment by aidlearning** [comment]
I think the question is your mobile phone have no root ,so you cannot write the  /dev/shm dir. of course ,you can reinstall the python , but I think it cannot solve the question. I think bette way is modified the codes slightly...

**Comment by SpringLincoln** [comment]
@2151330 can you pass me a v0.75 version please!

**Comment by SpringLincoln** [comment]
I can not install new version!

**Comment by SpringLincoln** [comment]
my email  642877180@qq.com thx!

**Comment by Charisma-enoal** [comment]
You sent the wrong email




------------------ 原始邮件 ------------------
发件人: "SpringLincoln"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 下午5:22
收件人: "aidlearning/AidLearning-FrameWork"<AidLearning-FrameWork@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [aidlearning/AidLearning-FrameWork] Any trouble in use AidLearning FrameWork can report here! (#1)




my email  642877180@qq.com thx!

**Comment by fzy657300** [comment]
| |
冯宗毅
|
|
fzy657300@163.com
|
签名由网易邮箱大师定制
On 9/3/2019 17:25，Murphy.Gee<notifications@github.com> wrote：
You sent the wrong email


你怎么知道我发错了，中是英语，兄die

------------------ 原始邮件 ------------------
发件人: "SpringLincoln"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 下午5:22
收件人: "aidlearning/AidLearning-FrameWork"<AidLearning-FrameWork@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [aidlearning/AidLearning-FrameWork] Any trouble in use AidLearning FrameWork can report here! (#1)




my email 642877180@qq.com thx!

**Comment by fzy657300** [comment]
| |
冯宗毅
|
|
fzy657300@163.com
|
签名由网易邮箱大师定制
On 9/3/2019 17:25，Murphy.Gee<notifications@github.com> wrote：
You sent the wrong email


？？？
------------------ 原始邮件 ------------------
发件人: "SpringLincoln"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 下午5:22
收件人: "aidlearning/AidLearning-FrameWork"<AidLearning-FrameWork@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [aidlearning/AidLearning-FrameWork] Any trouble in use AidLearning FrameWork can report here! (#1)




my email 642877180@qq.com thx!

**Comment by Charisma-enoal** [comment]
你应该是要Pytorch 0.75版本吧。这个github项目我都没关注过。怎么把邮件发给我了。




------------------ 原始邮件 ------------------
发件人: "zongyi"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 下午5:27
收件人: "aidlearning/AidLearning-FrameWork"<AidLearning-FrameWork@noreply.github.com>;
抄送: "Murphy.Gee"<359009471@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [aidlearning/AidLearning-FrameWork] Any trouble in use AidLearning FrameWork can report here! (#1)




 
 
 
 | |
 冯宗毅
 |
 |
 fzy657300@163.com
 |
 签名由网易邮箱大师定制
 On 9/3/2019 17:25，Murphy.Gee<notifications@github.com> wrote：
 You sent the wrong email
 
 
 你怎么知道我发错了，中是英语，兄die
 
 ------------------ 原始邮件 ------------------
 发件人: "SpringLincoln"<notifications@github.com>;
 发送时间: 2019年9月3日(星期二) 下午5:22
 收件人: "aidlearning/AidLearning-FrameWork"<AidLearning-FrameWork@noreply.github.com>;
 抄送: "Subscribed"<subscribed@noreply.github.com>;
 主题: Re: [aidlearning/AidLearning-FrameWork] Any trouble in use AidLearning FrameWork can report here! (#1)
 
 
 
 
 my email 642877180@qq.com thx!

**Comment by fzy657300** [comment]
不好意思 应该是某人的群发，回复以后都能收到！！


| |
冯宗毅
|
|
fzy657300@163.com
|
签名由网易邮箱大师定制
On 9/3/2019 17:30，Murphy.Gee<notifications@github.com> wrote：
你应该是要Pytorch 0.75版本吧。这个github项目我都没关注过。怎么把邮件发给我了。




------------------ 原始邮件 ------------------
发件人: "zongyi"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 下午5:27
收件人: "aidlearning/AidLearning-FrameWork"<AidLearning-FrameWork@noreply.github.com>;
抄送: "Murphy.Gee"<359009471@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [aidlearning/AidLearning-FrameWork] Any trouble in use AidLearning FrameWork can report here! (#1)







| |
冯宗毅
|
|
fzy657300@163.com
|
签名由网易邮箱大师定制
On 9/3/2019 17:25，Murphy.Gee<notifications@github.com> wrote：
You sent the wrong email


你怎么知道我发错了，中是英语，兄die

------------------ 原始邮件 ------------------
发件人: "SpringLincoln"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 下午5:22
收件人: "aidlearning/AidLearning-FrameWork"<AidLearning-FrameWork@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [aidlearning/AidLearning-FrameWork] Any trouble in use AidLearning FrameWork can report here! (#1)




my email 642877180@qq.com thx!

**Comment by anakinf** [comment]
不要发给我了




| |
anakin.s
邮箱：anakin.s@163.com
|

Signature is customized by Netease Mail Master

On 09/03/2019 17:32, zongyi wrote:
不好意思 应该是某人的群发，回复以后都能收到！！


| |
冯宗毅
|
|
fzy657300@163.com
|
签名由网易邮箱大师定制
On 9/3/2019 17:30，Murphy.Gee<notifications@github.com> wrote：
你应该是要Pytorch 0.75版本吧。这个github项目我都没关注过。怎么把邮件发给我了。




------------------ 原始邮件 ------------------
发件人: "zongyi"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 下午5:27
收件人: "aidlearning/AidLearning-FrameWork"<AidLearning-FrameWork@noreply.github.com>;
抄送: "Murphy.Gee"<359009471@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [aidlearning/AidLearning-FrameWork] Any trouble in use AidLearning FrameWork can report here! (#1)







| |
冯宗毅
|
|
fzy657300@163.com
|
签名由网易邮箱大师定制
On 9/3/2019 17:25，Murphy.Gee<notifications@github.com> wrote：
You sent the wrong email


你怎么知道我发错了，中是英语，兄die

------------------ 原始邮件 ------------------
发件人: "SpringLincoln"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 下午5:22
收件人: "aidlearning/AidLearning-FrameWork"<AidLearning-FrameWork@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [aidlearning/AidLearning-FrameWork] Any trouble in use AidLearning FrameWork can report here! (#1)




my email 642877180@qq.com thx!

**Comment by SpringLincoln** [comment]
@Charisma-enoal    lnyy510@163.com try this ,thx!

**Comment by aidlearning** [comment]
can u install the version 0.76?  pls give me the screenshot, I will fix it. thank u

**Comment by King7757** [comment]
I have installed but black screen appear whe  opening ?

**Comment by aidlearning** [comment]
when u install the app, and open it ,so it will show the screen like this 
![Screenshot_20190828-153558](https://user-images.githubusercontent.com/49776013/64260403-5e267e80-cf5d-11e9-8b9a-a8d990c3448f.jpg)
it will download the dependency of the deep learning autoly, when it download finished , it will start the desktop like this:
![Screen_11](https://user-images.githubusercontent.com/49776013/64260550-a645a100-cf5d-11e9-8f32-81b9c7360169.jpg)
can u provide the screen of the error?
if you cannot the question, you may delete the app and reinstall it using the newest version:
http://www.aidlearning.net/downloads/aidlux-09-04.apk
