### ISSUE TITLE
How to access SD card ?

### ISSUE THREAD

**Issue by KangKazumi** [aidlearning/AidLearning-FrameWork#101]

**Comment by aidlearning** [comment]
v0.86 will be released  which will support sdcard  and usb OTG..

**Comment by KangKazumi** [comment]
I see.
I also want to know how to prevent Aid-Desktop from starting automatically in the beginning.

Could you help me out?

**Comment by aidlearning** [comment]
You need hit the terminal icon only once on the desktop ,then can return to the terminal

**Comment by KangKazumi** [comment]
I think you've got me wrong.
I mean, all I want is to use terminal only, just like using termux.

Desktop is not convenient :
1, launching desktop takes time.
2, when I use other apps and then switch to the terminal, it will automatically switch to the desktop

**Comment by aidlearning** [comment]
next version will solve the question as planned

**Comment by KangKazumi** [comment]
Thank you, anyway.
