### ISSUE TITLE
I don't want GUI boot when app start. How to do?

### ISSUE THREAD

**Issue by v-wei40680** [aidlearning/AidLearning-FrameWork#102]
I don't need GUI desktop, I just want this python environment. How can i remove the load desktop code. When i try to set `startxfce=off`, the desktop just loading, i tap back back back many time, it will turn to terminal...

**Comment by aidlearning** [comment]
you need hit the terminal icon once  on the desktop ,then can return to the terminal

**Comment by v-wei40680** [comment]
> you need hit the terminal icon once on the desktop ,then can return to the terminal

- version: 0.8.5
- phone: huawei p30

When i change bash to zsh, it is hard to load desktop, just loading..., and it's hard to return terminal. The app can't use. I have to uninstall app, then reinstall it. so how to stop terminal auto turn into aid desktop. When i want to use GUI desktop, i will hit the icon.

**Comment by v-wei40680** [comment]
![Screenshot_20200507_165519_com aidlux](https://user-images.githubusercontent.com/48787443/81275090-c517ac80-9083-11ea-80f1-7c9c62059b8a.jpg)

**Comment by aidlearning** [comment]
next version will solve the question as planned
