### ISSUE TITLE
how can i change linux language

### ISSUE THREAD

**Issue by sandeshkumar20525** [aidlearning/AidLearning-FrameWork#103]
Please guide me

I don't understand chinese language

**Comment by aidlearning** [comment]
you can modify vi ~/.bashrc. You should comment out the sentence lang = zh cn.utf-8

**Comment by royal-tech** [comment]
How to commnet that

**Comment by aidlearning** [comment]
u

**Comment by ichit** [comment]
To comment it out, in the terminal first install nano text editor, then type nano / root/bashrc  scroll down untill you see it and then put #  sign before the line
