### ISSUE TITLE
My computer can't connect it via ssh though i upload my id_rsa and id_rsa.pub

### ISSUE THREAD

**Issue by QYHcrossover** [aidlearning/AidLearning-FrameWork#105]
![image](https://user-images.githubusercontent.com/47239807/81887387-8fb61600-95d1-11ea-8a1c-5dfe2b32bd77.png)

![image](https://user-images.githubusercontent.com/47239807/81887360-82992700-95d1-11ea-9857-ab82a7616d09.png)
the ip address and the usrname are all right
i don't know why is that?

**Comment by aidlearning** [comment]
pls ref:[如何使用各种ssh客户端密码连接方式连接Aidlearning](http://code.aidlearning.net:5283/article/84)

**Comment by QYHcrossover** [comment]
thanks，i have soloved it
