### ISSUE TITLE
How to install go,goland,clion,clang ctc,thank you

### ISSUE THREAD

**Issue by DiskGetor** [aidlearning/AidLearning-FrameWork#106]

**Comment by aidlearning** [comment]
you can use the apt install comand,for example
`apt install clang`

**Comment by DiskGetor** [comment]
> 您可以使用apt install comand，例如
> `apt install clang`

Thank you,clang was ok,how to install goland?

**Comment by aidlearning** [comment]
`apt install golang` command  is also working OK on aid
