### ISSUE TITLE
能不能出个精简版的apk

### ISSUE THREAD

**Issue by west-shell** [aidlearning/AidLearning-FrameWork#107]
软件太多 空间过大 不搞ai还用不上 能不能出个精简版 只保留基本的linux系统和桌面 桌面用i3之类的 很小巧 主要是用vscode
 因为termux的code-server有问题 只能用vim 
或者 给个精简的脚本 看看哪些能删除 自己运行下也行

**Comment by aidlearning** [comment]
yes, we will release a lite version 0.86-lite ,the version will be very small .pls wait ...we will be release soon

**Comment by west-shell** [comment]
嗯 精简以后进入桌面速度也会变快吧。可不可以设置默认直接进入终端？

**Comment by aidlearning** [comment]
yes，very faster！
