### ISSUE TITLE
各个库都没有

### ISSUE THREAD

**Issue by xinyang-go** [aidlearning/AidLearning-FrameWork#108]
在python3里import tensorflow, pytorch都会报错说no module

**Comment by aidlearning** [comment]
pls open the service  on the desktop and install it 
![Uploading Screenshot_20200613_103410_com.aidlux.jpg…](service)

**Comment by aidlearning** [comment]
![Uploading Screenshot_20200613_103410_com.aidlux.jpg…](service)

**Comment by aidlearning** [comment]
[!service screenshot ](https://cdn.nlark.com/yuque/0/2020/jpeg/726405/1592016110525-bc5dcd49-def1-40b0-a19b-73f1492da838.jpeg)
