### ISSUE TITLE
can't open the app

### ISSUE THREAD

**Issue by ThisisBillhe** [aidlearning/AidLearning-FrameWork#109]
I have been successfully running aidlearning for months,but when I want to open a new terminal today, it crushed. And I cant open the app now, it crushed when starting up the desktop.
By the way, how can I get access to the aidlearning files in Android? Im not rooted , so I can't get to the root directory

**Comment by aidlearning** [comment]
May I ask which version you are using? You can copy the files in aid learning to the / sdcard directory, which is your storage directory.If you have used aid for several months, it is estimated that too much storage space may be occupied, so you may need to clean up or back up your data to make aid occupy less storage  space

**Comment by ThisisBillhe** [comment]
thank u for replying me.It's v0.81 that I use.
Unfortunately,I cant open aidleaning now,so…how can I copy files from android environment using file explorer like RE?

**Comment by aidlearning** [comment]
It's too old version....can u connect  by ssh? if not ,You can return aid to terminal mode by repeatedly clicking the back key

**Comment by ThisisBillhe** [comment]
> It's too old version....can u connect by ssh? if not ,You can return aid to terminal mode by repeatedly clicking the back key

Sorry,I may not have made it clear...the aidlearning app crushed and  when I open it , it just crushed again. I can't stay in the terminal mode because it attempts to open the desktop when it just open up(and then crush).

**Comment by aidlearning** [comment]
May you need reinstall one newer version it may cannot launch the desktop,but it will not crush and keep terminal run background . SO , you can connect it by ssh
