### ISSUE TITLE
打不开任何应用

### ISSUE THREAD

**Issue by smartwell** [aidlearning/AidLearning-FrameWork#11]
安装好之后，能打开桌面但是打不开任何应用，就是黑屏然后卡在那儿，啥都没有，手机华为荣耀畅玩　８Ｃ　　安卓８．１

**Comment by aidlearning** [comment]
CPU is aarch64 ?fisrt time start,may be you need wifi to register in the first time.when you login successful,no need login again.can you give more details?

**Comment by aidlearning** [comment]
do you Open Camera Privileges for Mobile?

**Comment by smartwell** [comment]
@aidlearning  cpu骁龙632 我也注册登录了进去，进去以后点了 人脸检测，然后黑屏了，等了很久还是黑屏，没办法重启应用还是不行，重启手机也是不行啊，也打开了摄像机权限了

**Comment by aidlearning** [comment]
你能打开document图标吗？

**Comment by aidlearning** [comment]
我明白了，安装app后要下载700兆的文件依赖包，但是有时候连接会超时，导致文件没下载完，建议重新安装一遍，确保wifi网速。应该能解决这个问题

**Comment by smartwell** [comment]
又重新装了一遍，还是不行呢 ，那个压缩包，每次都是安装好才进的桌面

**Comment by smartwell** [comment]
document也打不开，而且还有个奇怪现象，终端里无法删除

**Comment by aidlearning** [comment]
我占用了8900端口，难道是别的app占用了这个端口？

**Comment by aidlearning** [comment]
你给app所有的权限了吗，不行给它所有权限

**Comment by smartwell** [comment]
给了，安装时全给了

**Comment by aidlearning** [comment]
装一个别的浏览器，并把新装的浏览器设成默认浏览器，再试一次，我也晕了！

**Comment by smartwell** [comment]
浏览器可以打开，桌面右下角的github 和官网能打开

**Comment by aidlearning** [comment]
设置能打开吗？

**Comment by smartwell** [comment]
嗯，点了以后，桌面上面提示获取了摄像机权限

**Comment by smartwell** [comment]
其他就没了

**Comment by aidlearning** [comment]
那是对的啊。我试了我的荣耀手机没问题

**Comment by aidlearning** [comment]
你是在网页上注册下载的app，还是在git上下载后安装后注册的？

**Comment by smartwell** [comment]
额，那好吧

**Comment by smartwell** [comment]
在app上注册安装的，没在网页上注册

**Comment by aidlearning** [comment]
那没有问题啊，你的手机的某个app可能占用了8900端口

**Comment by aidlearning** [comment]
建议换一个手机试一下，或则你把安装的过程录个视频给我，我帮您分析一下

**Comment by aidlearning** [comment]
你能打开terminal图标吗？然后在终端下能看到openssh等字样吗？如果看到了openssh等字样，说明就是因为网速慢导致的下载提前终止，这种情况下，是可以在好的wifi环境下重新安装解决的（先删除原先安装的app，不然解决不了这个问题，因为不删除已经安装的aidleading app，app不会重新下载依赖包）
