### ISSUE TITLE
怎么修改terminal的时间？

### ISSUE THREAD

**Issue by fdsuf** [aidlearning/AidLearning-FrameWork#112]
怎么修改软件的时间？
terminal里的时间好像时区不对，要怎么修改？

**Comment by aidlearning** [comment]
pls ref:
https://www.cnblogs.com/hushaoyan/archive/2018/06/08/9155045.html

**Comment by topxeq** [comment]
你好。是时区不对，不是要修改时间，正常应该用timedatectl set-timezone Asia/Shanghai命令来修改，date命令修改的是时间而不是时区。目前运行timedatectl 命令显示

```
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: 主机关闭
```
