### ISSUE TITLE
怎样修改时区（不是时间）

### ISSUE THREAD

**Issue by topxeq** [aidlearning/AidLearning-FrameWork#113]
你好，我的问题如 #112。是时区不对，不是要修改时间，正常应该用timedatectl set-timezone Asia/Shanghai命令来修改，date命令修改的是时间而不是时区。目前运行timedatectl 命令显示

```
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: 主机关闭
```

**Comment by aidlearning** [comment]
打开xfce，在里面的状态栏里的时间上点击右键，点击弹出的属性按钮进行设置，请参考图示如下：
[zone](https://cdn.nlark.com/yuque/0/2020/png/726405/1594537031469-7b27c7d3-3130-42dd-be0b-251357951308.png?x-oss-process=image%2Fresize%2Cw_1492)
