### ISSUE TITLE
document sdcard文件夹显示不全

### ISSUE THREAD

**Issue by Nibbbbbbbb** [aidlearning/AidLearning-FrameWork#114]
只显示到 .开头和a开头的文件夹，其他文件夹如何显示？  选倒序的话就只能显示z开头的

**Comment by aidlearning** [comment]
you can config it by the setting menu of the left bar on the documents

**Comment by Nibbbbbbbb** [comment]
Which setting? I can't find available

**Comment by Nibbbbbbbb** [comment]
> you can config it by the setting menu of the left bar on the documents

Which setting? I can't find available
