### ISSUE TITLE
how to control the audio in the phone  ? 

### ISSUE THREAD

**Issue by leechaowen** [aidlearning/AidLearning-FrameWork#119]
apt-get install mpv
mpv  xx.mp3 

it's not ok. is there anyone have solution ? Thanks.

**Comment by aidlearning** [comment]
if u using python to develop, you can easily control the audio by import android

**Comment by aidlearning** [comment]
python coding as following :
`import sl4a`
`droid=sl4a.Android()`
`droid.mediaPlay("/sdcard/a.mp3")`
