### ISSUE TITLE
Where can I find the model weights?

### ISSUE THREAD

**Issue by GokulNC** [aidlearning/AidLearning-FrameWork#12]
For all the example codes given here, where do I get the model weights from??

For example, for [MobileFaceNet](https://github.com/aidlearning/AidLearning-FrameWork/tree/master/examples/facencnn), I see only the `.json` file, but not the model weights of MXNet. Where can I find them?

Thanks :)

**Comment by aidlearning** [comment]
i upload it now, pls download!pls give me a star ,thank u!

**Comment by GokulNC** [comment]
Thank you soo much for your quick response!!
