### ISSUE TITLE
could not open multi terminal sessions ???

### ISSUE THREAD

**Issue by leechaowen** [aidlearning/AidLearning-FrameWork#120]
it's odd thing  could not open multi terminal sessions.    aidlux v0.86. Could you help to  fix it ? Thanks

**Comment by aidlearning** [comment]
ok ,will be fixed

**Comment by aidlearning** [comment]
[aid-0.86b2f3.apk](https://github.com/aidlearning/AidLearning-FrameWork/releases/download/v0.86/aid-0.86b2f3.apk) solved this bug.
