### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by danyja** [aidlearning/AidLearning-FrameWork#126]
when
apt update
apt upgrade

error found for perl perl-base python-minimal...

for example:
准备解压 .../python3.7-minimal_3.7.3-2+deb10u2_arm64.deb  ...
正在解压 python3.7-minimal (3.7.3-2+deb10u2) 并覆盖 (3.7.3-2+deb10u1) ...
dpkg: 处理归档 /var/cache/apt/archives/python3.7-minimal_3.7.3-2+deb10u2_arm64.deb (--unpack)时出错：
 无法获取 ./usr/bin/python3.7 的状态(正准备安装该文件): 不允许的操作
dpkg-deb: 错误: 粘贴 子进程被信号(断开的管道) 终止了
在处理时有错误发生：
 /var/cache/apt/archives/python3.7-minimal_3.7.3-2+deb10u2_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by aidlearning** [comment]
You should not use the upgrade command as much as possible because of the interdependence and coexistence of various packages in Linux system. Once used, it may cause errors in the installed packages. But you can use update, which is safe

**Comment by west-shell** [comment]
可以定一个忽略名单吗 升级时自动忽略 别的可以一键升级
