### ISSUE TITLE
如何卸载程序，休眠运行

### ISSUE THREAD

**Issue by kamike** [aidlearning/AidLearning-FrameWork#128]
我之前用的termux，偶然发现了AID，发现很强大，立马卸载termux。我装的精简版的，使用过程中发现想卸载地图软件，还有一些其他没必要的软件，关闭通知栏的天气预报。

还有回到桌面，或者关闭屏幕休眠之后浏览器访问cloud_ip都没反应了，应该是可以设置的

没有找到哪里可以卸载，也搜索过issues没有看到相关的讨论。感谢作者

**Comment by aidlearning** [comment]
pls view  to

**Comment by kamike** [comment]
好的，谢谢了
