### ISSUE TITLE
How can I Import my code and data

### ISSUE THREAD

**Issue by starhou** [aidlearning/AidLearning-FrameWork#13]
I can't find the '/sdcard' folder in the phone folder. It seems like that could only copy my code and paste in a new file. While the data I need couldn't do like this.

**Comment by aidlearning** [comment]
I'm sorry to ask you what type of mobile phone you have. Generally , mobile phone should have sdcard. It's not necessarily called sdcard. It might be called storage or something like that. You just need to copy your code to the directory of your mobile phone. If not, there is an alternative:
You can open the URL in the pc:
Http://192.168.1.6:8910/upload (change IP address 192.168.1.6 to your IP address) upload your files to the / root directory of your mobile phone, and then you copy to any directory you want.

**Comment by starhou** [comment]
Really thanks bill, my mobile phone is MI8 Lite. I have had a try but got a err like that ‘The input folder is invalid, please change another’，I don't have a root authority，and I even couldn't find where the app's source folder.

**Comment by aidlearning** [comment]
dont neet root .this method is only upload the file one by one.cannot upload a dir.may be you can zip a dir as tar file and upload it.then hit the terminal .in the terminal ,you can tap the command : cd /root;ls 
so you can see the upload the files.

**Comment by starhou** [comment]
WOW! I know how can I import my own code and data, I have found the sdcard folder under the Aid learning‘document , it is my own storage space of my moblie phone. Now I can work it. 
I have another question that I find matplotlib doesn't work,  which to say that I couldn't plot figure. I would like to konw if you would add this.

**Comment by aidlearning** [comment]
Congratulations！
Next version will be added matplotlib!will be release in the next month.
Now , may you can use cvs (from cv import *) instead the matplotlib to show the result.

**Comment by aidlearning** [comment]
pls ref:
https://github.com/aidlearning/AidLearning-FrameWork/tree/master/cvs

**Comment by starhou** [comment]
This is really a fun software, I'm looking forward to next version. Come on！

**Comment by aidlearning** [comment]
thank u for your support and encouragement
