### ISSUE TITLE
grep: /proc/version: 权限不够

### ISSUE THREAD

**Issue by xielm12** [aidlearning/AidLearning-FrameWork#130]
我安装code_1.50.0-1602050515_arm64.deb后，运行code时出现如下错误：
root@localhost:~# code
grep: /proc/version: 权限不够
You are trying to start Visual Studio Code as a super user which isn't recommended. If this was intended, please specify an alternate user data directory using the `--user-data-dir` argument.

**Comment by aidlearning** [comment]
you can su demo by passwd demo to switch the user

**Comment by aidlearning** [comment]
vscode already buildin. U don't  install again
