### ISSUE TITLE
怎么没人问，支持docker吗

### ISSUE THREAD

**Issue by aogg** [aidlearning/AidLearning-FrameWork#133]
真心希望有

**Comment by aidlearning** [comment]
docker还在测试中，可能需要一段时间适配

**Comment by aogg** [comment]
要是有难点可以试下docker in docker

**Comment by shutter-cp** [comment]
![image](https://user-images.githubusercontent.com/37921589/119265145-418e1680-bc18-11eb-88ad-6400fcad296a.png)

无法启动

**Comment by abc3127552** [comment]
同楼上, 找了老半天, 设置镜像也不能启动docker

**Comment by van-chin** [comment]
> docker还在测试中，可能需要一段时间适配

@aidlearning 有没有 docker 相关的时间计划 Roadmap

**Comment by aidlearning** [comment]
docker需要root手机+定制rom才能实现

**Comment by aogg** [comment]
无root虚拟机，这有的吗
