### ISSUE TITLE
请问如何自定义背景图片？

### ISSUE THREAD

**Issue by erikaemma** [aidlearning/AidLearning-FrameWork#134]
1. 网上有到/root/.os/OS.js/dist的但是我没有dist文件夹；
2. 自己试了一试，找到了/root/User/mac/plugins/theme_switcher下面，修改js文件添加我自己的图片，但是在图片管理器中依旧找不到我自己添加的图片
3. 论坛发不了帖子，一直提示“糟糕，出错啦！请刷新页面重试。”

**Comment by aidlearning** [comment]
你必须同时指定两张图片，一张小的缩略图、一张真正的背景图：比如这样：bg1_small.jpg bg1.jpg
<img width="794" alt="image" src="https://user-images.githubusercontent.com/49776013/99334140-a2304580-28bb-11eb-93fe-ff98b37f2428.png">
