### ISSUE TITLE
平板选择屏幕显示不全的问题

### ISSUE THREAD

**Issue by mapleby** [aidlearning/AidLearning-FrameWork#135]
![image](https://user-images.githubusercontent.com/45815225/99384598-9f107600-290a-11eb-8753-e372ba20b978.png)

我的平板是matePai 10.8,使用效果来讲确实不错，就是显示会不全

**Comment by mapleby** [comment]
被遮挡住了

**Comment by aidlearning** [comment]
嗯，这个下一版本解决
