### ISSUE TITLE
vscode提示不能按照go插件

### ISSUE THREAD

**Issue by 1925473403** [aidlearning/AidLearning-FrameWork#137]
vscode安装go插件时提示
Unable to install 'golang.go' extension because it is not compatible with the current version of VS Code (version 1.44.2).
![image](https://user-images.githubusercontent.com/10141057/100174356-2d18cd80-2ec4-11eb-88e0-642aae18095b.png)

**Comment by aidlearning** [comment]
next version we try fix the bug
