### ISSUE TITLE
求助：Aid Learning安装完成后/usr/bin目录下的perl和python无法访问

### ISSUE THREAD

**Issue by hjianhao** [aidlearning/AidLearning-FrameWork#138]
提示Operation not permitted.  
这样无法升级，也无法安装git
用户是root用户，没法chmod，没法lsattr等，这个怎么解决？
这样就没法用了。

版本 b0.86b2f3

**Comment by aidlearning** [comment]
you can mv xxx xxx.bak or rm xxx to remove this files.
