### ISSUE TITLE
storage外置内存卡，只能读取，不能写入

### ISSUE THREAD

**Issue by Angel0726** [aidlearning/AidLearning-FrameWork#139]
### 1. 背景需求
因为闲置手机的配置较低，ROM太小。希望能够使用storage的外置内存卡，存储数据库中的数据。

### 2.效果
目前已经购买外置128g的tf内存卡，内存卡可以读取与写入。但是aidlearning只能访问storage，进行写入操作的时候显示没有权限。使用chmod命令无法解决

### 3.问题所在
aidlearning软件没有向安卓系统申请完整的内存卡操作权限。希望aidlearning能够申请并获取外置SD卡的写入权限

**Comment by aidlearning** [comment]
next version will fixed
