### ISSUE TITLE
There are two show windows in the screen,I just need one.

### ISSUE THREAD

**Issue by macunshi** [aidlearning/AidLearning-FrameWork#14]
Thanks for your working on the APP! It is awesome！
When I run the python code of example, there are two show windows in the screen, I know the bottom one is generated by python code, but where is the top window from?I hope there is just one window or frame which is linked to my python code.
Thank you!

**Comment by aidlearning** [comment]
the top windows is show the the frame not being processed . if you dont tp show the windows of the top,you can tap the zoom button of the bottom.

**Comment by aidlearning** [comment]
i will release the next version which will be surpport this by setting .may be 2 weeks later

**Comment by macunshi** [comment]
I want to write an application, and the application's frame is completely controlled by my own code, so I don't want to have other frames.
Thans for your answer.

**Comment by aidlearning** [comment]
give me your emails ,I send u files ,you can get your need.

**Comment by macunshi** [comment]
201752071014@std.uestc.edu.cn
This project is very interesting, so I think I wIl have fun, thank you!

**Comment by aidlearning** [comment]
thank u ! if you love it ,pls give me star!

**Comment by macunshi** [comment]
i just light the star!

**Comment by aidlearning** [comment]
thank u very much! I modify the hide the windows now.i will send u after 10 minutes

**Comment by aidlearning** [comment]
have sent!pls check it
