### ISSUE TITLE
vscode? why not docker?

### ISSUE THREAD

**Issue by better319** [aidlearning/AidLearning-FrameWork#140]
vscode why not docker?
docker needed

**Comment by VISHAWANATH953** [comment]
to implement docker it was some little bit hard @better319  but you can use it with qemu emulation bro.

**Comment by aidlearning** [comment]
when your phone is rooted, aid support docker

**Comment by VISHAWANATH953** [comment]
yah! it was rooted

**Comment by VISHAWANATH953** [comment]
So I think this was time to implement this and need to close this repo @aidlearning
