### ISSUE TITLE
A suggestion to change github project title from "AidLearning-Framework" to "AidLearning for Linux-Python-AI code development on Android" 

### ISSUE THREAD

**Issue by awaisnaz** [aidlearning/AidLearning-FrameWork#141]
I installed this project on my android. And I am blown away. I wanted a sexy solution to run python deeplearning code on android. But after weeks of searching on Google for Termux, Pyrdoid, Google Colab in local runtime, and host or errors after using them, and the fact that tensorflow's python code can't run on Android, and only Linux, but available Linux emulators on android are buggy wrt tensorflow. This project is excellent.

Just one suggestion, change the title to make it SEO friendly, and people can easily find it in Github Search and Google Search. Because I couldn't find it by conventional search.

**Comment by aidlearning** [comment]
good idea!
