### ISSUE TITLE
Unfavorable language? How to change the language fully to english !?

### ISSUE THREAD

**Issue by AIHorizion** [aidlearning/AidLearning-FrameWork#142]
Dear Devs, it is a pleasure to use such incredible app, but there are some things which needs to be resolved, the gui is quite good, but many settings are written in Chinese language which is unfavorable to many, pls kindly try to change the whole language system into English which will be appreciated!

Looking forward for your actions.
Thanks

**Comment by aidlearning** [comment]
you can modify ~/.bashrc or /root/.bashrc . You should comment out the sentence lang = zh cn.utf-8:

**Comment by AIHorizion** [comment]
> you can modify ~/.bashrc or /root/.bashrc . You should comment out the sentence lang = zh cn.utf-8:

Thanks for the help !

**Comment by TopsyKretz415** [comment]
How do you change the language in the app to english
