### ISSUE TITLE
x86 bug

### ISSUE THREAD

**Issue by meny233** [aidlearning/AidLearning-FrameWork#145]
Welcome to AidLux!/data/data/com/aidlux/files/usr/bin/login[23]: /data/data/com.aidlux/files/usr/bin/bash: not executable: 64-bit ELF file

[Process completed (code 1) - press Enter]
Aid Learning 不支持 x86 架构

**Comment by aidlearning** [comment]
yes! x86 is not in list

**Comment by meny233** [comment]
那我如何在Android x86中安装Linux系统呢?
How to install Linux in Android x86?
