### ISSUE TITLE
能不能增加对R语言的支持

### ISSUE THREAD

**Issue by hlblade** [aidlearning/AidLearning-FrameWork#147]
尝试安装Debian的R studio server和jupyter的R语言支持都没有成功
谢谢

**Comment by aidlearning** [comment]
will be try...

**Comment by leechaowen** [comment]
新版本是可以支持的
 install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'，'IRkernel'))

root@localhost:~# R

R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: aarch64-unknown-linux-gnu (64-bit)

R是自由软件，不带任何担保。
在某些条件下你可以将其自由散布。
用'license()'或'licence()'来看散布的详细条件。

R是个合作计划，有许多人为之做出了贡献.
用'contributors()'来看合作者的详细情况
用'citation()'会告诉你如何在出版物中正确地引用R或R程序包。

用'demo()'来看一些示范程序，用'help()'来阅读在线帮助文件，或
用'help.start()'通过HTML浏览器来看帮助文件。
用'q()'退出R.

> library("IRkernel")
> IRkernel::installspec()
[InstallKernelSpec] Installed kernelspec ir in /root/.local/share/jupyter/kernels/ir
>
