### ISSUE TITLE
是否可以考虑支持pyjnius在AidLearning-FrameWork上运行？

### ISSUE THREAD

**Issue by redstoneleo** [aidlearning/AidLearning-FrameWork#149]
是否可以考虑支持pyjnius在AidLearning-FrameWork上运行？
主要是用来接触更多、更新的Android API，要知道SL4A应该已经算是停滞不前的技术了吧

供参考：
https://github.com/kivy/pyjnius
https://pyjnius.readthedocs.io/en/stable/android.html

**Comment by aidlearning** [comment]
will be support!
