### ISSUE TITLE
python3 and use Pc  to code

### ISSUE THREAD

**Issue by majestichou** [aidlearning/AidLearning-FrameWork#15]
1 How can I code on Pc by using this app? Can you tell me more details? Thank you.
2 How to upgrade to python3

**Comment by aidlearning** [comment]
1.if you want code in the pc 👍 :you only open  http://192.168.1.8:8900/ ,if your mobile's ip is 192.168.1.8
(you can see your mobile phone's ip using the ifconfig command in the terminal of aid app)
2. python3 is supported in the next version(now already finished),will be release in few days later.

**Comment by aidlearning** [comment]
Any way, your only one window showing version is working?

**Comment by majestichou** [comment]
> @majestichou Any way, your only one window showing version is working?

yes, it works well. 
But I can't open the ip of my phone on pc by using the method you give. It shows me "ERR_CONNECTION_REFUSED". 
And can I use anaconda on the app?

**Comment by aidlearning** [comment]
your mobile and the pc must in same network.for example : if your mobile ip is 192.168.1.5 and your pc's ip is 192.168.2.5,may be cannot connect!  make sure mobile phone and the pc in the same NAT

**Comment by majestichou** [comment]
yeh, my pc and phone are both in the same network and their ip is the same. Do I need some other operations to do, such as root?

**Comment by aidlearning** [comment]
make sure the aid learning app is opened ,maybe you don't keep the app alive...

**Comment by majestichou** [comment]
> make sure the aid learning app is opened ,maybe you don't keep the app alive...

PC can connect to mobile by using ssh-keygen. Your readme.md tells us to do this. Do I need to use ssh-keygen? And how to use ssh-keygen? Can you give me more details?

**Comment by aidlearning** [comment]
if you want code in pc by web, you don't need ssh-keygen.just open the explore to code in the web.
if you want user remote connect to the mobile by pc ,you need open the terminal of pc and tap the command :ssh-keygen to create the safe files .when you  finished the command, you can intput:cd ~/.ssh to see the created the files. you must open the mobile's ip:8910 to upload the safe files to mobile phone.
last, you can open the terminal of the pc ,and tap command:
ssh u0_a201@192.168.1.6 -p8022 
(if your mobile's ip is 192.168.1.6.)
to connect the mobile phone.

**Comment by majestichou** [comment]
> if you want code in pc by web, you don't need ssh-keygen.just open the explore to code in the web.
> if you want user remote connect to the mobile by pc ,you need open the terminal of pc and tap the command :ssh-keygen to create the safe files .when you finished the command, you can intput:cd ~/.ssh to see the created the files. you must open the mobile's ip:8910 to upload the safe files to mobile phone.
> last, you can open the terminal of the pc ,and tap command:
> ssh u0_a201@192.168.1.6 -p8022
> (if your mobile's ip is 192.168.1.6.)
> to connect the mobile phone.

Thanks a lot !!! You are so nice. 
I find another bug: I can sign in on the aidlearning.net by chorme. But I can't sign in on the app and I am sure my account and key is right.

**Comment by aidlearning** [comment]
the account need mail's activated! you may need log in your emails ,and activated ,so you can login in. because we make your email is valid, so we need activate.

**Comment by majestichou** [comment]
> the account need mail's activated! you may need log in your emails ,and activated ,so you can login in. because we make your email is valid, so we need activate.

My email is valid. And the bug also exits.

**Comment by aidlearning** [comment]
in your email box ,can you see aidleanrning.net activated emails? if you recieved,you must paster the url to Activate it.

**Comment by majestichou** [comment]
Yes, I have activated my emails. Maybe in the next app version, you can add the function of forgetting the user name or it can be log in by email.

**Comment by aidlearning** [comment]
yes！good idea，I will add the function.
