### ISSUE TITLE
v0.87F1在Honor X10上无法启动

### ISSUE THREAD

**Issue by FlyMan2004** [aidlearning/AidLearning-FrameWork#153]
在手机上启动后，软件显示为黑屏；用浏览器链接，所有软件无法启动

**Comment by aidlearning** [comment]
pls retry it . our login server is something wrong ,have already fixed

**Comment by FlyMan2004** [comment]
> pls retry it . our login server is something wrong ,have already fixed

Should I reboot my device? Or reinstall it?

**Comment by FlyMan2004** [comment]
> pls retry it . our login server is something wrong ,have already fixed

Thanks a lot. My problem has been solved.
