### ISSUE TITLE
小米k305g(android11)安装v0.87F1后，vscode打不开

### ISSUE THREAD

**Issue by kekemuyu** [aidlearning/AidLearning-FrameWork#154]
如题，vscode的服务已安装并且执行。但是客户端一直在转圈。
我的另一部手机是android10安装后没有问题，vscode可以正常运行

**Comment by aidlearning** [comment]
你可以尝试下面的步骤：
`apt  remove nodejs`
`apt install npm`
然后用下面命令启动
` cd  /.vscode.aidbuild;node out/node/entry.js --port 8008 --auth none`

**Comment by aidlearning** [comment]
will be release the fixed version ....
