### ISSUE TITLE
求助，小米MIUI 12.0.1无法安装

### ISSUE THREAD

**Issue by ethan-enhe** [aidlearning/AidLearning-FrameWork#155]
安卓版本**10**

- 安装lite版到一半说没有存储权限，但实际已经给了存储权限
- 安装pro和full版安装到20%直接闪退

**Comment by aidlearning** [comment]
或许你可以提供更多信息供参考

**Comment by ethan-enhe** [comment]
github上图片有时会挂，故每个图片也弄了个链接

图一：安装lite版报错 [pic](https://i.loli.net/2021/02/05/6rHDLa1bCGBwYjz.png)
![1.png](https://i.loli.net/2021/02/05/6rHDLa1bCGBwYjz.png)

图二：安装full版进度条页面 [pic](https://i.loli.net/2021/02/05/xcMKpD9NFLn4e7m.png)
![2.png](https://i.loli.net/2021/02/05/xcMKpD9NFLn4e7m.png)

图三：安装full版进度条加载到20%后闪退，弹出要求相机权限 [pic](https://i.loli.net/2021/02/05/rWGpZFVlkgeovT8.png)
![3.png](https://i.loli.net/2021/02/05/rWGpZFVlkgeovT8.png)

图四：我的权限设置 [pic](https://i.loli.net/2021/02/05/3oAHP8mdWU71uRr.png)
![4.png](https://i.loli.net/2021/02/05/3oAHP8mdWU71uRr.png)

请问还需要提供啥信息？谢谢！

**Comment by aidlearning** [comment]
我们在小米11上测试过0.87版，是可以工作的。qq群里有人也是小米系统，但是是因为存储空间不够导致无法安装成功，你可以检查一下你的存储空间是否足够

**Comment by ethan-enhe** [comment]
存储空间是够的，这个是新手机，前几天看了一下，应该至少还有45G存储空间

**Comment by aidlearning** [comment]
可以到qq群里交流，录屏解决一下 Aid Learning中文官方群 群号:111245605

**Comment by ethan-enhe** [comment]
好的
