### ISSUE TITLE
任务栏的窗口菜单没有关闭一个窗口的选项

### ISSUE THREAD

**Issue by dave-yxw** [aidlearning/AidLearning-FrameWork#156]
右击任务栏上的窗口图标显示的菜单没有关闭该窗口的选项，只能全部关闭。这个不大有好。
下面图中的case，窗口上的x按钮被菜单栏挡住了，也没法单独关闭该窗口了。

![aid-bug2](https://user-images.githubusercontent.com/9003308/107867477-204db980-6eb6-11eb-8760-3384d7c29bf1.PNG)

**Comment by aidlearning** [comment]
谢谢反馈，会逐步修复这些适配上的问题
