### ISSUE TITLE
0.87F3gpu加速真好用

### ISSUE THREAD

**Issue by gislele** [aidlearning/AidLearning-FrameWork#158]
新增的gpu加速功能确实快，调用也简单import tflite_gpu模块，(model_path,inShape,outShape,4,0) # 4表示4个cpu线程，0表示gpu，-1表示cpu，1表示NNAPI 线程数在aid上设置的4线程，还可以设置线程数和是否使用gpu+cpu模式；性能比之前的0.86提升了好几倍，不错不错！

**Comment by aidlearning** [comment]
thanks
