### ISSUE TITLE
performance degradation after running overnight

### ISSUE THREAD

**Issue by kaishijeng** [aidlearning/AidLearning-FrameWork#16]
I run your face recognition application on my android tablet overnight and the app becomes quite slow (you can see video refresh on the screen quite slow). I can see a couple frames/sec at the beginning. 
Are you aware of  this issue?

**Comment by aidlearning** [comment]
I'm sorry to ask you what type of mobile phone you have. Generally ,   you have 4kernel cpu,i.use the openblas to speed it.if your cpu is low level <4 kernel,may be more slowly!

**Comment by kaishijeng** [comment]
I don't think it is # of core issue because this slowdown happens when your app runs overnight.
Below is my table model and cpu sku

Teclast M89 7.9 Inch IPS Air 2048X1536 OGS PowerVR GX6250 MTK8176 Hexa-core 2.1GHz 8.0MP 2.4G/5G 3GB RAM 32GB ROM Double Speaker

**Comment by aidlearning** [comment]
i see your means runing at night. i donnt be aware it. i will try

**Comment by aidlearning** [comment]
I tried it last night, not because the performance of the system is degraded, but because face recognition is less effective in finding faces at night, so it feels slower.

**Comment by kaishijeng** [comment]
My symptom is different. IN the morning which has pretty of light, video frame update on the screen is so slow.

**Comment by aidlearning** [comment]
ok,i will test it again, will be reported for u
