### ISSUE TITLE
v0.87F1 版本安装完成后，打开设置提示unkown the request这是咋回事呢

### ISSUE THREAD

**Issue by wu737** [aidlearning/AidLearning-FrameWork#160]
vscode也用不了
[upl-image-preview url=http://new.aidlearning.net/assets/files/2021-04-09/1617981097-561108-image.png]

**Comment by wu737** [comment]
记错了是v0.87F3版本
手机红米K30 Pro 
安卓11  MIUI 12.2.3

**Comment by aidlearning** [comment]
可能是你的8080端口被别的app占用，建议重启手机，先打开aid后再测试！
