### ISSUE TITLE
vscode版本低，代码面板模糊

### ISSUE THREAD

**Issue by BoltLi** [aidlearning/AidLearning-FrameWork#161]
如题，最新的vscode已经到1.55了，而这里面使用的还是1.44。
另外，当点击vscode左边的图标（例如插件或者调试）后，代码面板会模糊，无法恢复。
![Screenshot_20210415_214715_com aidlux](https://user-images.githubusercontent.com/42888380/114884639-80ba9200-9e38-11eb-98c9-44cb7244ad25.jpg)

**Comment by aidlearning** [comment]
不知道你安装的版本是多少呢？最新的0.87F3版本内置的是VS Code: v1.52.1，并且没有你说的模糊的问题，并且图标也改了，建议你安装最新版
