### ISSUE TITLE
ios version needed

### ISSUE THREAD

**Issue by Misaka17032** [aidlearning/AidLearning-FrameWork#163]
Is it possible to make it adapt to ios devices? Considering that not everyone has an Android device, the development of an ios version is necessary.

**Comment by Gary-code** [comment]
iOS版本无法上线到APP store，APP store对于这种虚拟机的产品都无法过审，等六月份的WWDC再说



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月10日(周一) 凌晨0:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [aidlearning/AidLearning-FrameWork] ios版适配请求 (#163)




 
是否能够适配ios设备？考虑到不是每个人都有Android设备，ios版的开发是必要的。
