### ISSUE TITLE
Application stops 

### ISSUE THREAD

**Issue by NelsonGuiamba** [aidlearning/AidLearning-FrameWork#165]
Your spication stops when installing at 20% always
![Screenshot_20210515-235525](https://user-images.githubusercontent.com/71399799/118379226-0cab0f80-b5d9-11eb-8e1e-cce786f69d01.jpeg)
My device info:
-----------------
          OS: Android 8.1.0 
          Host: TCL 5033G
         Kernel: 4.4.95+
  ..CPU: MT6739WA (4) @ 1.2
Memory: 588MiB / 885MiB

**Comment by aidlearning** [comment]
make your phone have 6g free storage and try it again...
