### ISSUE TITLE
终端设置自己的shell脚本时提示not been booted with systemd as init system

### ISSUE THREAD

**Issue by Terry-Lzz** [aidlearning/AidLearning-FrameWork#169]
System has not been booted with systemd as init system (PID 1). Can't operate.
在aid中想安装自己的shell服务并设置自启动。但是启动服务失败，出现这个提示。经搜索查询，一般是在wsl或者docker遇到这种问题，请问在aidlearning中该如何解决？

**Comment by aidlearning** [comment]
pls give me more details pic or log....I guess the reason is your phone no root ,so aid cannot permit to  operate.
