### ISSUE TITLE
SSH Connection timed out

### ISSUE THREAD

**Issue by boydream123** [aidlearning/AidLearning-FrameWork#171]
Successful install ssh and configure sshd_config
content is as follows：
Port 5656
ListenAddress 192.168.0.105
PermitRootLogin yes
PasswordAuthentication yes

but when i try to connect, but it doesn't work

ssh demo@192.168.0.105 -p 5656
ssh: connect to host 192.168.0.105 port 5656: Connection timed out

at the same time, i try to use root, but the result is the same

ssh root@192.168.0.105 -p 5656
ssh: connect to host 192.168.0.105 port 5656: Connection timed out

Could you please tell me how to configure this? thank you!

**Comment by aidlearning** [comment]
you should using `/etc/init.d/ssh restart ` to restart the ssh config. after this, you can use the  ssh demo@192.168.0.105 -p 5656 to connect...

**Comment by boydream123** [comment]
I've tried to do it, but it doesn' work.

root@localhost:/etc/ssh# /etc/init.d/ssh restart
[ ok ] Restarting OpenBSD Secure Shell server: sshd.


(base) PS C:\Users\boydr> ssh demo@192.168.0.105 -p 5656
ssh: connect to host 192.168.0.105 port 5656: Connection timed out

**Comment by aidlearning** [comment]
pls ref this url:
[http://new.aidlearning.net/d/84](http://new.aidlearning.net/d/84)
