### ISSUE TITLE
怎么连接实验室的linux远程服务器用

### ISSUE THREAD

**Issue by 630362055** [aidlearning/AidLearning-FrameWork#172]

**Comment by aidlearning** [comment]
ssh user@xx.xx.xx.xx -p port

**Comment by 630362055** [comment]
> ssh [username@xx.xx.xx.xx](mailto:username@xx.xx.xx.xx) -p port

Vscode怎么连接远程服务器？我的windows上的vscode使用的拓展是remote ssh，但是aid里的vscode好像没有这个拓展
