### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by LuSany** [aidlearning/AidLearning-FrameWork#173]
after I running apt-get upgrade, at the end of the update process，there is an error: "/var/cache/apt/archives/unzip_6.0-23+deb10u2_arm64.deb    E: Sub-process /usr/bin/dpkg returned an error code (1)"

I followed the solution on the internet that creating a new info directory under /var/lib/dpkg, it's also has same error. how to deal with this problem?

Phone: Huawei P30
OS: Harmony OS 2

**Comment by zxq432** [comment]
AID Learning 0.87F3,  Android10

========================================
root@localhost:/home# apt upgrade
正在读取软件包列表... 完成
正在分析软件包的依赖关系树
正在读取状态信息... 完成
正在计算更新... 完成
下列软件包将被升级：
  unzip
升级了 1 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
需要下载 0 B/166 kB 的归档。
解压缩后会消耗 0 B 的额外空间。
您希望继续执行吗？ [Y/n]
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
(正在读取数据库 ... 系统当前共安装有 171953 个文件和目录。)
准备解压 .../unzip_6.0-23+deb10u2_arm64.deb  ...
正在解压 unzip (6.0-23+deb10u2) 并覆盖 (6.0-23+deb10u1) ...
dpkg: 处理归档 /var/cache/apt/archives/unzip_6.0-23+deb10u2_arm64.deb (--unpack)时出错：
 无法获取 ./usr/bin/unzip 的状态(正准备安装该文件): 不允许的操作
dpkg-deb: 错误: 粘贴 子进程被信号(断开的管道) 终止了
在处理时有错误发生：
 /var/cache/apt/archives/unzip_6.0-23+deb10u2_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

root@localhost:/home# ls -l /usr/bin 2>/dev/null| grep zip |grep ^l
l?????????? ? ?    ?           ?             ? bunzip2
l?????????? ? ?    ?           ?             ? bzip2
l?????????? ? ?    ?           ?             ? gunzip
l?????????? ? ?    ?           ?             ? unzip
l?????????? ? ?    ?           ?             ? zipinfo

root@localhost:/home# ls -l /usr/bin/unzip
ls: 无法访问'/usr/bin/unzip': 不允许的操作

=======================

it seems as if these 5 files have file mode problem marked by many "?" of the file properties. chmod and chown do not work for these files to change ? to the proper values.

**Comment by aidlearning** [comment]
can u using command `rm -rf bunzip2` ? if success ,you can apt install unzip again

**Comment by zxq432** [comment]
rm -fr bunzip2 works and apt upgrade OK now.

**Comment by zxq432** [comment]
rm -fr bunzip2 works and apt upgrade OK now.

**Comment by zxq432** [comment]
rm -fr bunzip2 works and apt upgrade OK now.

**Comment by LuSany** [comment]
> rm -fr bunzip2 works and apt upgrade OK now.

I run the command 'rm -rf /usr/bin/bunzip2' and it's also the same error as before. how did you do to solve the problem?

**Comment by LuSany** [comment]
@aidlearning 
I run the command 'rm -rf /usr/bin/bunzip2' and excute apt-get install unzip, it's also the same error as before. how to solve the problem?

**Comment by aidlearning** [comment]
0.88 version fixed this bug，will be release soon ,pls wait...
