### ISSUE TITLE
请问如何在tasker shell调用python

### ISSUE THREAD

**Issue by tsiens** [aidlearning/AidLearning-FrameWork#175]
之前用的是termux，直接在代码-shell中运行 /data/data/com.termux/files/usr/bin/python test.py就行，
现在换aidlearning，在com.aidlux搜索‘python’，发现下面两个，
/data/data/com.aidlux/files/usr/bin/python2.7
/data/data/com.aidlux/files/python/bin/python
执行都是报错，
17.29.01/E 运行Shell命令:  -> 
17.29.01/E 运行Shell命令:  -> 
17.29.01/E 运行Shell命令:  -> 
17.29.01/Shell runBackground /data/data/com.aidlux/files/python/bin/python /storage/emulated/0/Tasker/test.py root: true timeout: 1000
17.29.01/Shell start process-thread ID 503
17.29.01/E add wait type Shell1 time 2147483647
17.29.01/E add wait type Shell1 done
17.29.01/E add wait task
17.29.01/E 错误: 1

**Comment by aidlearning** [comment]
我不太了解tasker shell，你可以直接在aid中运行python test.py就好了。不需要/data/data/com.aidlux/files/python/bin/python   /storage/emulated/0/Tasker/test.py

**Comment by tsiens** [comment]
> 我不太了解tasker shell，你可以直接在aid中运行python test.py就好了。不需要/data/data/com.aidlux/files/python/bin/python /storage/emulated/0/Tasker/test.py

不一定是tasker shell吧，就安卓的shell，请问是否能外部调用aidlearning的python，用tasker是条件触发调用py程序（比如连接到家庭网络，就执行py脚本）
