### ISSUE TITLE
v0.87F3 无法使用frpc

### ISSUE THREAD

**Issue by zark005** [aidlearning/AidLearning-FrameWork#176]
在v0.87F3上安装frp后运行./frpc  -c frpc.ini会报非法指令
运行SakuraFrp会报段错误
之前的版本都是正常的

**Comment by aidlearning** [comment]
we test it ,will give the fix solution ...

**Comment by fakeboboliu** [comment]
用 [这个](https://getfrp.sh/d/frpc_linux_arm64_noupx) 即可
