### ISSUE TITLE
How to add support OpenCL

### ISSUE THREAD

**Issue by Saikatsaha1996** [aidlearning/AidLearning-FrameWork#177]
My device XIAOMI MI 10T
In my mobile already available OpenCL driver
libOpenCL.so
After installing this software can't find libOpenCL.so
How can it support OpenCL?

Help wanted
Thank you

**Comment by aidlearning** [comment]
aid have support OpenCL default. you can using tflite_gpu module which merged OpenCL to calling the gpu of the arm ...pls ref the /home/examples-gpu/ in the aid

**Comment by Saikatsaha1996** [comment]
> aid have support OpenCL default. you can using tflite_gpu module which merged OpenCL to calling the gpu of the arm ...pls ref the /home/examples-gpu/ in the aid

Thank you for your response
Actually my gpu Adreno 650, OpenCL 2.0 supported..
And I wand to implement my Vendor OpenCL to aid learning...

**Comment by Saikatsaha1996** [comment]
> aid have support OpenCL default. you can using tflite_gpu module which merged OpenCL to calling the gpu of the arm ...pls ref the /home/examples-gpu/ in the aid

Please see this.. about my problem..
libOpenCL.so available but Clinfo showing number of platform 0
![Screenshot_20210725-223219](https://user-images.githubusercontent.com/72664192/126907334-32bf48ed-0409-4f2b-a17a-3011fdbac3a9.jpg)


![Screenshot_20210725-223159](https://user-images.githubusercontent.com/72664192/126907332-6571ee95-364f-495f-9092-66d53e4683b2.jpg)

**Comment by Saikatsaha1996** [comment]
> aid have support OpenCL default. you can using tflite_gpu module which merged OpenCL to calling the gpu of the arm ...pls ref the /home/examples-gpu/ in the aid

Please see this... I am trying to compile libOpenCL.so file
Cp dynamic library libopencl.so to aid learning
But when I Compile getting error like this any solution ?
![IMG_20210725_233738](https://user-images.githubusercontent.com/72664192/126908940-426f7670-871b-42ad-8989-908a6dfaea10.jpg)

**Comment by aidlearning** [comment]
Sorry,OpenCL compile method  in aid is now ready for open...
