### ISSUE TITLE
How about add support for qualcomm dsp hexagon

### ISSUE THREAD

**Issue by peyer** [aidlearning/AidLearning-FrameWork#178]
I heard that Qualcomm has authorized to Google for running TFLite with dsp backend on Hexagon devices, will you add  support for qualcomm dsp hexagon?

**Comment by aidlearning** [comment]
Yes！Aid support TFLite with dsp backend on Hexagon devices like this:
` tflite.NNModel(model_path,inShape,outShape,4,2) `  2 means Hexagon mod
