### ISSUE TITLE
Can your fastpose model transfer to ncnn?

### ISSUE THREAD

**Issue by zys1994** [aidlearning/AidLearning-FrameWork#18]
I am interested in your fastpose, Can your fastpose model transfer to ncnn?

**Comment by aidlearning** [comment]
fastpose models have some layers don't be supported by ncnn. so I modified it in the ncnn.i have converted it to ncnn sucessfully. but it be used to a project of business.so.....

**Comment by zys1994** [comment]
ok. i got it. you are so excellent. The faceRegconition model you released is 99.5% in lfw?

**Comment by aidlearning** [comment]
99.68%

**Comment by zys1994** [comment]
it looks like good. the input 112*112? and the align method is the same as the insightface?

**Comment by aidlearning** [comment]
yes, input 112*112 convert to (-1,1) like insight face
