### ISSUE TITLE
hardlink count not equal to hardlinked file count

### ISSUE THREAD

**Issue by zxq432** [aidlearning/AidLearning-FrameWork#180]
hardlink count less than hardlinked file count, it seems as if 2 hidden hardlinked files  automatically generated by aidlux are not counted, whose file name have ".l2s." as prefix, and one has "0001" as suffix, the other has '0001.000#" as suffix. there are no such two hardlinked hidden files on an ordinary linux system. 

when a hidden hardlink is deleted, the left  hardlinks will lose hardlink and become not accessible. this situation always lead to problems when apt upgrade debian of aidlux, or when installing packages. especially, when installing packages from source code, the problem shows up more often and with a faillure result.

====the following are the steps to show the issue:

root@localhost:/tmp/tmp# date>x
root@localhost:/tmp/tmp# ls -ali
总用量 16
 533961 drwx------.  2 root root 3488 8月   2 23:08 .
 207221 drwx------. 49 root root 8192 8月   2 23:04 ..
1104231 -rw-------.  1 root root   43 8月   2 23:08 x
root@localhost:/tmp/tmp# ln x y
root@localhost:/tmp/tmp# ls -ali
总用量 28
 533961 drwx------.  2 root root 3488 8月   2 23:08 .
 207221 drwx------. 49 root root 8192 8月   2 23:04 ..
1104231 -rw-------.  2 root root   43 8月   2 23:08 .l2s.x0001
1104231 -rw-------.  2 root root   43 8月   2 23:08 .l2s.x0001.0002
1104231 -rw-------.  2 root root   43 8月   2 23:08 x
1104231 -rw-------.  2 root root   43 8月   2 23:08 y
root@localhost:/tmp/tmp# ln x z
root@localhost:/tmp/tmp# ls -ali
总用量 32
 533961 drwx------.  2 root root 3488 8月   2 23:09 .
 207221 drwx------. 49 root root 8192 8月   2 23:04 ..
1104231 -rw-------.  3 root root   43 8月   2 23:08 .l2s.x0001
1104231 -rw-------.  3 root root   43 8月   2 23:08 .l2s.x0001.0003
1104231 -rw-------.  3 root root   43 8月   2 23:08 x
1104231 -rw-------.  3 root root   43 8月   2 23:08 y
1104231 -rw-------.  3 root root   43 8月   2 23:08 z
root@localhost:/tmp/tmp# find . -type l
./.l2s.x0001
./z
./x
./y
root@localhost:/tmp/tmp# cat x
2021年 08月 02日 星期一 23:49:59 UTC
root@localhost:/tmp/tmp# rm .l2s.x0001
root@localhost:/tmp/tmp# cat x
cat: x: 没有那个文件或目录
root@localhost:/tmp/tmp# ls -ali
ls: 无法访问'z': 不允许的操作
ls: 无法访问'x': 不允许的操作
ls: 无法访问'y': 不允许的操作
总用量 16
 533961 drwx------.  2 root root 3488 8月   2 23:48 .
 207221 drwx------. 49 root root 8192 8月   2 23:04 ..
1104231 -rw-------.  3 root root   43 8月   2 23:08 .l2s.x0001.0003
      ? l??????????  ? ?    ?       ?             ? x
      ? l??????????  ? ?    ?       ?             ? y
      ? l??????????  ? ?    ?       ?             ? z
root@localhost:/tmp/tmp#

**Comment by aidlearning** [comment]
yes, you are right, we will fixed in the next version

**Comment by ichit** [comment]
other tablet archecture @aidlearning . please is there the posibility of having aidlearning apk that can be installed on other phone or tablets with archecture other than aarch64. I have a 32bit tablet and it does not install on it. thanks
