### ISSUE TITLE
Failed to initialize libdc1394

### ISSUE THREAD

**Issue by ouening** [aidlearning/AidLearning-FrameWork#19]
手机型号：小米8
系统：MIUI10.3
安卓：9
当执行cvs或其他文件夹下的.py文件时，提示错误：
root@localhost:/home/singlepose# python webpose.py      libdc1394 error: Failed to create juju: opendir: Permission denied                                              libdc1394 error: Failed to initialize libdc1394         open the cam:0 ...                                      import tensorflow.....wait...                            * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)                                                       127.0.0.1 - - [26/May/2019 16:04:56] "GET / HTTP/1.1" 200 -                                                     You choose to stop me.
请问有有效的解决方案吗？还有一个问题是注册之后迟迟没有收到验证邮箱，导致无法登录。

**Comment by aidlearning** [comment]
注册要到邮箱里激活才能生效，有可能激活邮件会进垃圾箱，: Failed to initialize libdc1394 是opencv的警告信息，不影响使用，import tensorflow 有点慢，你要多等几秒。

**Comment by aidlearning** [comment]
邮箱已给您手动激活了，可以登陆运行了吗？

**Comment by ouening** [comment]
谢谢作者!可以运行了，只不过有些例子运行很慢，比如姿态检测那个，还以为是软件的bug，需要近半分钟才有反应
