### ISSUE TITLE
运行 pip 命令报错

### ISSUE THREAD

**Issue by hillerliao** [aidlearning/AidLearning-FrameWork#196]
比如运行 `pip list`

提示 `OSError: Cannot find path to android app folder`

怎么办？

环境：
MIUI 12.5.4
AidLux 从小米应用商店下载的，版本号为  0.92

**Comment by aidlearning** [comment]
你应该更新了pip导致的错误，最新的pip有bug，详情可以咨询qq群里的aid-desktop咨询解决方式
