### ISSUE TITLE
文档中存在错误

### ISSUE THREAD

**Issue by yzyyz1387** [aidlearning/AidLearning-FrameWork#197]
文档中
 - 快速开始
   - apt命令
     -  安装软件包

存在错误 

>检查室友有损坏的依赖包

**Comment by yzyyz1387** [comment]
https://docs.aidlux.com/#/quickstart?id=apt命令

**Comment by aidlearning** [comment]
than u! fixed:https://docs.aidlux.com/#/intro/aid-linux
