### ISSUE TITLE
Great jobs! this is a Linux with Gui running in the android

### ISSUE THREAD

**Issue by qidiso** [aidlearning/AidLearning-FrameWork#2]
Great jobs! this is a Linux with Gui running on the android,termux is  only a terminal running in  the android.Aidl is powerful ! it can save many time to config the AI Framework like caffe/tf/mxnet/keras...
how about pytorch?have the plan to surpport it ?

**Comment by aidlearning** [comment]
Yes! but need some time! torch is good framework of ai, but  to arm ,is not friendly!
