### ISSUE TITLE
sqlite3 in python3

### ISSUE THREAD

**Issue by kaishijeng** [aidlearning/AidLearning-FrameWork#20]
python3 has builtin sqlite3 module. However, python3 in your latest release (yesterday) doesn't have this. Can you check it?

Thanks,

**Comment by qfmail** [comment]
sqlite not build in...you can install it by pip3 install?


 
---Original---

**Comment by kaishijeng** [comment]
I tried to install pip3 install pysqlite. But got an error.
   ERROR: pysqlite is not supported on Python 3. When using Python 3, use the sqlite3 module from the standard library.


>>>>>

  Downloading http://mirrors.aliyun.com/pypi/packages/42/02/981b6703e3c83c5b25a829c6e77aad059f9481b0bbacb47e6e8ca12bd731/pysqlite-2.8.3.tar.gz (80kB)
     |████████████████████████████████| 81kB 477kB/s
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: pysqlite is not supported on Python 3. When using Python 3, use the sqlite3 module from the standard library.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-7t5fo2u9/pysqlite/

**Comment by aidlearning** [comment]
I will try it....

**Comment by kaishijeng** [comment]
It looks like the latest version of your release still has this issue.
Can you make sure your python3 includes sqlite3?

Thanks,

**Comment by aidlearning** [comment]
however ,I try many times, it cannot  solved....sorry!

**Comment by kaishijeng** [comment]
Not sure where how you get python3? Sqlite3 should be built in the python3 by default.
Thanks,
FC

**Comment by aidlearning** [comment]
I download from the official website:
I make it from the src of 3.6.4

**Comment by kaishijeng** [comment]
You may need to install libsqlite3-dev (or compiling from sqlite3 source code) first before you compile python3.6.4

Thanks,

**Comment by aidlearning** [comment]
ok, I try it ......

**Comment by dobefore** [comment]
maybe  another  sql software `pymysql`(a support for mysql is suitable for you

**Comment by aidlearning** [comment]
pip3 install pysqlite3 is now working:
pip3 install pysqlite3
Collecting pysqlite3
  Downloading http://mirrors.aliyun.com/pypi/packages/63/f9/d768ba1522852672b49f4ea3cf8c9f21743cc3a0c966fd4809add6133e67/pysqlite3-0.4.1.tar.gz (40kB)
    100% |████████████████████████████████| 40kB 7.3MB/s 
Building wheels for collected packages: pysqlite3
  Running setup.py bdist_wheel for pysqlite3 ... done
  Running setup.py clean for pysqlite3
Installing collected packages: pysqlite3
  Running setup.py install for pysqlite3 ... done
Successfully installed pysqlite3

**Comment by aidlearning** [comment]
have building in the version >0.84
