### ISSUE TITLE
compile and install python 3.10.1 cause aid-desktop can't run

### ISSUE THREAD

**Issue by LY1806620741** [aidlearning/AidLearning-FrameWork#201]
I need python3.9+ in aidlux. So I install it by source code. Then I found that aid-desktop keep loading. Click three times into error mode, and then run `startx` is the same.

**Comment by sevilen** [comment]
Don't change the default python3，you can use ln -s python3.9  /xxx/python3.9/bin/python3.9

**Comment by LY1806620741** [comment]
这个问题已经过去很长时间了，可能已经失效了, 先关上它。This problem has passed for a long time, and may have invalid. Close it first
