### ISSUE TITLE
‘/dev/net’: Permission denied

### ISSUE THREAD

**Issue by xulei-Itachi** [aidlearning/AidLearning-FrameWork#203]
我想使用openconnect，错误提示如下：
mkdir: cannot create directory ‘/dev/net’: Permission denied
mknod: /dev/net/tun: No such file or directory
Failed to open tun device: Permission denied
Set up tun device failed

**Comment by Gavinluo** [comment]
@xulei-Itachi  抱歉使用这种方式与你联系，我想问下，关于你这个问题最后有什么结论，我也遇到了相同的问题，给我的程序造成了很大性能困扰，或者我们邮件沟通 gavin.luo.628@qq.com ，
![image](https://user-images.githubusercontent.com/1356485/151160573-d3397a59-47f2-4d83-8bf1-1002760d1abd.png)
