### ISSUE TITLE
关于网络安全问题的考虑。Considerations on network security

### ISSUE THREAD

**Issue by LY1806620741** [aidlearning/AidLearning-FrameWork#204]
cloud_ip功能是一个极好用的功能，但是他通过局域网http协议明文传输密码，这在大局域网例如校园是十分不安全的，别人通过抓包可以获取你的密码（特别是弱密码），并获得访问你个人手机数据的权限。我的建议是增加ip访问白名单机制，对所有请求ip列表进行临时授权。这个建议是否可行，或实用，如果有更好的方法请告知我。cloud_ IP is an excellent function, but it transmits passwords in plaintext through the LAN HTTP protocol, which is very unsafe in large LAN such as campus. Others can obtain your password (especially weak password)  by capturing packets, and access your personal mobile phone data. My suggestion is to add IP access whitelist mechanism to temporarily authorize all request IP lists. Whether this suggestion is feasible or practical, please let me know if there is a better method.（Lazy translator from Baidu）

**Comment by aidlearning** [comment]
已经在开发计划中了

**Comment by LY1806620741** [comment]
另外，在版本aidlux1.2,我发现cloud_ip是默认打开的，并且noVnc是常驻，当开启xfce4时访问http://ip:6080/vnc.html竟然可以免密登录，这实在是太危险了

**Comment by aidlearning** [comment]
good idea!

**Comment by LY1806620741** [comment]
该问题并没有解决
version:1.3.0.477
aid desktop:1.5.1

**Comment by LY1806620741** [comment]
我看不到任何改进，如果可以,要不我来开发? I can't see any improvement. Can I develop it?
