### ISSUE TITLE
How to complie  this project? Is it really open-source?

### ISSUE THREAD

**Issue by ghost** [aidlearning/AidLearning-FrameWork#205]
I met with some problem in using AidLearning , and I find it's an open-source project, so I can read the source and try to find out the causes of the problem.
But after download the src file, I found nothing about how to compile this project, and even the core code about AidLearning。
The apk size is as large as 405MB, but the sourcecode size from github is only 65 MB, and the image files occupy 47MB.
That's what the document says, this project is released under the GPLv3 license, isn't it ? 
Or do I have some misunderstanding about this project?
But if it's eally not an open-source project, please remove the "GPLv3" tag in the Licence file, I hope people will not be misled again by such things.

**Comment by aidlearning** [comment]
will be released source code  for later...
