### ISSUE TITLE
 sony xperia 1 ii (root) is not supported...

### ISSUE THREAD

**Issue by ubun222** [aidlearning/AidLearning-FrameWork#208]
打开aidlux后黑屏。。为什么同样是安卓手机，我的就不行，已按照24后的zygisk隐藏root

**Comment by tangzeyu7** [comment]
> 打开aidlux后黑屏。。为什么同样是安卓手机，我的就不行，已按照24后的zygisk隐藏root

使用`alpha`版本的Magisk试看看

**Comment by ubun222** [comment]
> > 打开aidlux后黑屏。。为什么同样是安卓手机，我的就不行，已按照24后的zygisk隐藏root
> 
> 使用`alpha`版本的Magisk试看看
