### ISSUE TITLE
我觉得参考代码需要备注我的名字

### ISSUE THREAD

**Issue by 1099438829** [aidlearning/AidLearning-FrameWork#213]
这是一个很棒的项目，我很喜欢已经装载到我的平板电脑了，后续考虑装载在我的开发板上，但是使用的时候我发现贵团队使用了我的代码，（云桌面参考了我的macui的代码，也就是win10ui优化版的代码），虽然是git SATA协议，gitee mit协议，但是我还是觉得有署名权利的，我也很乐意参与到项目中改善一些体验的ui样式问题

**Comment by fannyhy** [comment]
&nbsp; &nbsp; &nbsp; &nbsp;非常感谢你的来信，方便的话请加我微信：13438886218，我们可以及时沟通！
&nbsp; &nbsp; &nbsp; &nbsp;祝好！





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月2日(周二) 下午5:37
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [aidlearning/AidLearning-FrameWork] 我觉得参考代码需要备注我的名字 (Issue #213)




 
这是一个很棒的项目，我很喜欢已经装载到我的平板电脑了，后续考虑装载在我的开发板上，但是使用的时候我发现贵团队使用了我的代码，（云桌面参考了我的macui的代码，也就是win10ui优化版的代码），虽然是git SATA协议，gitee mit协议，但是我还是觉得有署名权利的，我也很乐意参与到项目中改善一些体验的ui样式问题
