### ISSUE TITLE
Crash on Mix2s

### ISSUE THREAD

**Issue by WhiteUmaru** [aidlearning/AidLearning-FrameWork#215]
<img width="678" alt="image" src="https://user-images.githubusercontent.com/29397850/191188144-bda45e45-fbee-4caf-a2d5-33cb482f5365.png">

**Comment by WhiteUmaru** [comment]
launch with crash

**Comment by tangzeyu7** [comment]
[AidLux 安装丨启动失败原因总结](https://community.aidlux.com/postDetail/453)
You can take a look at the post of the official forum.
