### ISSUE TITLE
无法进行Usb串口连接

### ISSUE THREAD

**Issue by KiSetsuFu-PuLiN** [aidlearning/AidLearning-FrameWork#216]
机型：Huawei P30

尝试使用aidlux内的python通过手机Usb串口连接树莓派Pico进行通讯，但不成功。

所使用的树莓派Pico本身可在Windows下通过串口工具PuTTY以115200的波特率正常进行Usb串口通讯。
在使用aidlux的时候尝试使用其python模块功能 droid = android.Android() 进行Usb连接，droid.startSearchSerialUsb()可以正常找到所连接的树莓派Pico设备，但随后使用功能 droid.connectSerialUsb(portNum = 0, deviceId = {刚刚操作找到的设备Id号}, bauRate = 115200) 功能却一直无法返回正确值。（并且手机没有显示AidLux有申请使用USB设备）

然而使用 droid.connectUsb() 却将树莓派Pico识别成Arduino智能小车并成功建立了连接，并且手机有显示AidLux有申请使用USB设备。

**Comment by gislele** [comment]
参考下https://blog.csdn.net/xuxer110/article/details/124395476，使用connectSerialUsb可以提前将usb的OTG权限打开，0是usb连接
