### ISSUE TITLE
How can I slove ”not executable: 64-bit ELF file” when install

### ISSUE THREAD

**Issue by X1angfeng** [aidlearning/AidLearning-FrameWork#22]
![TIM图片20190604000316](https://user-images.githubusercontent.com/36064720/58816482-34a73f80-865c-11e9-88db-1dcfdf4383ef.jpg)

**Comment by aidlearning** [comment]
AidLearning can run on Android devices supports the CPU of Arm64(aarch64). not support the 32 bit cpu .so if u install the aidlearming in the android of arm32,will be report the "not executable " erro. how about your mobile's config?

**Comment by X1angfeng** [comment]
oh,thanks.I'm understand。
