### ISSUE TITLE
can't connect to mobile phone with VSCode on pc

### ISSUE THREAD

**Issue by jhyuuu** [aidlearning/AidLearning-FrameWork#220]
when I use ssh connection, the vscode stay on the "Copying VS Code Server to host with scp" page

**Comment by jhyuuu** [comment]
stay on the "Copying VS Code Server to host with scp" page

**Comment by jhyuuu** [comment]
when I use ssh connection, the vscode stay on the "Copying VS Code Server to host with scp" page

**Comment by aidlearning** [comment]
vscode scp not support on aidlux yet, but on lists for upgrade!
