### ISSUE TITLE
AidLux1.3.0卡启动页

### ISSUE THREAD

**Issue by TheWhiteDog9487** [aidlearning/AidLearning-FrameWork#221]
设备：Redmi K30 5G
系统：MIUI 13.0.3稳定版
已经Root，方案是Magisk 25.2，开启了Zygisk+LSPosed+Shamiko，将AidLux加入了隐藏Root的列表（遵守排除也试过，无效）

问题：第一次会进命令行，第二次开始卡启动页，也就是这样：
![Screenshot_2023-01-25-13-04-31-020_com.aidlux.jpg](https://user-images.githubusercontent.com/60037547/214484923-a5ee5858-915b-4574-b9a5-a918ff34a144.jpg)

Error模式说是有一个脚本的一条指令找不到程序，也就是这个：
![Screenshot_2023-01-25-13-04-39-761_com.aidlux.jpg](https://user-images.githubusercontent.com/60037547/214485160-a42db4c4-43a7-48d0-8f25-80d2f32ff2e9.jpg)
清除所有数据无效，这个有办法修吗？

**Comment by sevilen** [comment]
检查一下安装时存储权限给了吗？尝试重新安装给予存储权限

**Comment by TheWhiteDog9487** [comment]
> 检查一下安装时存储权限给了吗？尝试重新安装给予存储权限

没有用，重新安装了一次，第一次打开前手动允许了存储权限，应用内的权限也是同意。结果完全一样。

**Comment by sevilen** [comment]
第一次安装和重新安装过程中，解压有什么错误吗?

**Comment by tangzeyu7** [comment]
手机的存储还够么?看现象有感觉是有linux文件没解压完,AidLux装上去了还大概需要2G的空间来初始化linux环境.

**Comment by TheWhiteDog9487** [comment]
> 第一次安装和重新安装过程中，解压有什么错误吗?
> 手机的存储还够么?看现象有感觉是有linux文件没解压完,AidLux装上去了还大概需要2G的空间来初始化linux环境.
没毛病，我刚开这个问题的时候试了（重装，清数据等）好几次，包括刚才重装一次，都是一样的问题。但我打算直接用录屏复现的时候，这次重装后没有问题，我多测试几次，看看是不是有什么地方不对。
存储空间的话76.1/128GB，不可能不够。

**Comment by TheWhiteDog9487** [comment]
坏了，现在我反而没法复现了。有可能是之前下载的包有损坏。
我先close吧，如果有新的信息再开。
