### ISSUE TITLE
Force closes on OnePlus 10T - Android 13

### ISSUE THREAD

**Issue by lmservas** [aidlearning/AidLearning-FrameWork#224]
I've tried the latest version, going back through 1.0 as well and none of them will open - just get a force close on my OnePlus 10T (CPH2417) w/Android 13.

**Comment by aidlearning** [comment]
Can you provide a screenshot of the problem so that we can easily locate it? We agree that the most likely error is caused by the process being killed on Android 12,Thank you for your feedback！
