### ISSUE TITLE
force close in android 13

### ISSUE THREAD

**Issue by kyzsuukii** [aidlearning/AidLearning-FrameWork#229]
i have issue same with #224

![Screenshot_20230910-140105_LogFox.png](https://github.com/aidlearning/AidLearning-FrameWork/assets/110718021/d0362734-2d5e-413d-9bf6-cb898f2791fe)

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/lavender/lavender:13/TQ2A.230505.002.A1/1828:userdebug/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-09-10 14:00:53.072757575+0800
Process uptime: 2s
Cmdline: com.aidlux
pid: 7431, tid: 7508, name: com.aidlux  >>> com.aidlux <<<
uid: 10361
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x00000000000007a0
Cause: null pointer dereference
    x0  0000000000000000  x1  0000007cd1b0f116  x2  0000000000000000  x3  0000000000000000
    x4  0000007cd0859cc0  x5  0000007de390612c  x6  0000007cd0859cb0  x7  00000000acd979ce
    x8  00000000b6a287f2  x9  00000000000007a0  x10 00000000b6a287f2  x11 00000000000007a0
    x12 0000000000000000  x13 0000000000004100  x14 fffffffffc000000  x15 0000000000000000
    x16 0000007de3917d10  x17 0000007de3899a60  x18 0000007cd097c000  x19 0000007cd1b3bd58
    x20 0000007cd1b3b558  x21 0000000000000045  x22 0000007cd1a56000  x23 0000000000001d07
    x24 0000007cd1a55cb0  x25 0000007cd1a55cb0  x26 0000007cd1a55ff8  x27 00000000000fc000
    x28 00000000000fe000  x29 0000007cd1a55c10
    lr  0000000000000000  sp  0000000000000000  pc  00000000000007a0  pst 0000000000000000
backtrace:
      #00 pc 00000000000007a0  <unknown>
      #01 pc 0000000000000000  <unknown>
```

**Comment by tangzeyu7** [comment]
Is the device rooted?

**Comment by kyzsuukii** [comment]
> Is the device rooted?

yes is rooted

**Comment by tangzeyu7** [comment]
> > Is the device rooted?
> 
> yes is rooted

AidLux 1.4.0 is no longer supported on rooted devices.

**Comment by kyzsuukii** [comment]
> > > Is the device rooted?
> > 
> > yes is rooted
> 
> AidLux 1.4.0 is no longer supported on rooted devices.

any alternative??

**Comment by M1saka10010** [comment]
> > > Is the device rooted?
> > 
> > 
> > yes is rooted
> 
> AidLux 1.4.0 is no longer supported on rooted devices.

Why?

**Comment by tangzeyu7** [comment]
In order to avoid additional security problems, AidLux is root-proofed by its security hardening service provider.

> > > > Is the device rooted?
> > > 
> > > 
> > > yes is rooted
> > 
> > 
> > AidLux 1.4.0 is no longer supported on rooted devices.
> 
> Why?

In order to avoid additional security problems, AidLux is root-proofed by its security hardening service provider.

**Comment by kyzsuukii** [comment]
> In order to avoid additional security problems, AidLux is root-proofed by its security hardening service provider.
> 
> > > > > Is the device rooted?
> > > > 
> > > > 
> > > > yes is rooted
> > > 
> > > 
> > > AidLux 1.4.0 is no longer supported on rooted devices.
> > 
> > Why?
> 
> In order to avoid additional security problems, AidLux is root-proofed by its security hardening service provider.

what about hidden root like using shamiko its will work??

**Comment by tangzeyu7** [comment]
It won't work. Even if it's hidden, it'll be detected.

**Comment by kyzsuukii** [comment]
> It won't work. Even if it's hidden, it'll be detected.

i see. i will switch to kernelSU now

**Comment by M1saka10010** [comment]
> > In order to avoid additional security problems, AidLux is root-proofed by its security hardening service provider.
> > > > > > Is the device rooted?
> > > > > 
> > > > > 
> > > > > yes is rooted
> > > > 
> > > > 
> > > > AidLux 1.4.0 is no longer supported on rooted devices.
> > > 
> > > 
> > > Why?
> > 
> > 
> > In order to avoid additional security problems, AidLux is root-proofed by its security hardening service provider.
> 
> what about hidden root like using shamiko its will work??

 In my case open zygisk and exclude Aidlux can work

**Comment by kyzsuukii** [comment]
> > > In order to avoid additional security problems, AidLux is root-proofed by its security hardening service provider.
> > > > > > > Is the device rooted?
> > > > > > 
> > > > > > 
> > > > > > yes is rooted
> > > > > 
> > > > > 
> > > > > AidLux 1.4.0 is no longer supported on rooted devices.
> > > > 
> > > > 
> > > > Why?
> > > 
> > > 
> > > In order to avoid additional security problems, AidLux is root-proofed by its security hardening service provider.
> > 
> > what about hidden root like using shamiko its will work??
> 
>  In my case open zygisk and exclude Aidlux can work

thanks, i will try

**Comment by tangzeyu7** [comment]
> In my case open zygisk and exclude Aidlux can work

Good, you can use it! Can you tell me the version of AidLux you are using? When 1.4.0 was first released, it was tested that versions before 1.4.0 could be used with zygisk to hide the root, but since 1.4.0 it doesn't work anymore.

**Comment by M1saka10010** [comment]
> > In my case open zygisk and exclude Aidlux can work
> 
> Good, you can use it! Can you tell me the version of AidLux you are using? When 1.4.0 was first released, it was tested that versions before 1.4.0 could be used with zygisk to hide the root, but since 1.4.0 it doesn't work anymore.

1.40

**Comment by tangzeyu7** [comment]
> 1.4.0

Well, that may have been improved with the zygisk update. That's good.

**Comment by kyzsuukii** [comment]
![Screenshot_20230920-113915_AidLux.png](https://github.com/aidlearning/AidLearning-FrameWork/assets/110718021/245d671e-1699-4f4d-8f75-86615430665f)


well shamiko working fine to hidden root

**Comment by tangzeyu7** [comment]
> well shamiko working fine to hidden root

Great!
