### ISSUE TITLE
login/sign up

### ISSUE THREAD

**Issue by A-Random-Person-on-Github** [aidlearning/AidLearning-FrameWork#236]
how do i login or sign up

**Comment by A-Random-Person-on-Github** [comment]
evrytime i open the app there is a login page

**Comment by aidlearning** [comment]
you can click skip(very small in the bottom)

**Comment by A-Random-Person-on-Github** [comment]
Can you pont to the button i cant seem to find it
![Screenshot_20240331_201407_AidLux](https://github.com/aidlearning/AidLearning-FrameWork/assets/124088073/a44f8c89-075c-4a15-80c7-e60e3081a71a)

**Comment by qzd1989** [comment]
![haha](https://github.com/aidlearning/AidLearning-FrameWork/assets/3345241/75945361-961c-4e2b-9c64-fc1f6a016aac)
另外,你们好久没更新项目了. 底层debian能更新一下吗? 现在已经debian12了.
