### ISSUE TITLE
Internal Server Error The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application

### ISSUE THREAD

**Issue by ouening** [aidlearning/AidLearning-FrameWork#24]
OS: 小米8 MIUI10.3.3稳定版
Android: 9

Hi, when I ran the example 'faceID' and submit a chinese name, error happens:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application

Can someone fix it?

**Comment by aidlearning** [comment]
Thank you for reporting this bug. Can you tell me if I can work under the English name submit? I think it's a language coding problem. It's scrambled on my phone, but Internal Server Error didn't show up.
