### ISSUE TITLE
Can you provide a more detailed introduction to GUI customization?

### ISSUE THREAD

**Issue by big2pig** [aidlearning/AidLearning-FrameWork#25]
Can you provide a **more detailed i**ntroduction to GUI customization?

**Comment by aidlearning** [comment]
I'm further developing and upgrading the customization of gui. Now it's beta version. I plan to provide a more powerful and flexible GUI customization interface in two weeks. I'll provide detailed documentation then. Thank you.

**Comment by aidlearning** [comment]
www.aidlearning.net
