### ISSUE TITLE
I use ssh to connect my mobilephone ,and do this : "apt-get update" 

### ISSUE THREAD

**Issue by wdweidao** [aidlearning/AidLearning-FrameWork#26]
root@localhost:/home# apt-get update
Ign:1 http://deb.debian.org/debian stretch InRelease
Hit:2 http://deb.debian.org/debian stretch Release
Err:3 http://deb.debian.org/debian stretch Release.gpg
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010 NO_PUBKEY EF0F382A1A7B6500
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://deb.debian.org/debian stretch Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010 NO_PUBKEY EF0F382A1A7B6500
W: Failed to fetch http://deb.debian.org/debian/dists/stretch/Release.gpg  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010 NO_PUBKEY EF0F382A1A7B6500
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by aidlearning** [comment]
I think you should enter commands on a computer terminal rather than on a mobile phone:
SSH u0_a311@192.168.31.134-p8022 assumes that the network IP of your phone is 192.168.31.134.
By the way, what version are you installing? There should be no "apt update" issue in installing the latest version

**Comment by iyangsheng** [comment]
I have the same problem. Have you solved it now?

**Comment by iyangsheng** [comment]
@aidlearning I did "apt update" on my mobile phone. The error message was the same.

**Comment by wdweidao** [comment]
@aidlearning yeah！I enter commands on my computer，no problem ssh connect , error caused by "apt-get update".

**Comment by aidlearning** [comment]
apt install command working? in my mobile ,I find the apt update is not working and apt install is working. I will fixed the bugs about the apt update

**Comment by wdweidao** [comment]
@aidlearning "apt install" works well

**Comment by jasonber** [comment]
I have the same problem.....

**Comment by aidlearning** [comment]
I fixed in the next version ,will be released in the next few days. you can instal the package by apt install command, apt install working....

**Comment by aidlearning** [comment]
gpg --keyserver pgpkeys.mit.edu --recv-key 8B48AD6246925553
gpg -a --export 8B48AD6246925553 | apt-key add -

gpg --keyserver pgpkeys.mit.edu --recv-key 7638D0442B90D010
gpg -a --export 7638D0442B90D010 | apt-key add -

gpg --keyserver pgpkeys.mit.edu --recv-key EF0F382A1A7B6500
gpg -a --export EF0F382A1A7B6500 | apt-key add -

**Comment by aidlearning** [comment]
or:
apt-key adv --keyserver pgpkeys.mit.edu  --recv-keys 8B48AD6246925553
gpg -a --export 8B48AD6246925553 | apt-key add -

**Comment by aidlearning** [comment]
new version 0.73 now released! the version solved the update bug!
