### ISSUE TITLE
how to reduce the size of AidLearning?

### ISSUE THREAD

**Issue by angleseeu** [aidlearning/AidLearning-FrameWork#27]
A great app for learning Deep Learning. Programming on mobile phones is also very interesting and strongly supportive! 
It is suggested that one or more platforms can be installed without downloading tf, pytorch, Caffe and mxnet all at once. After all, the capacity of mobile phones is still limited.

**Comment by aidlearning** [comment]
Thank you very much for your praise. I will make the system more stable and useful. Now I am working to reduce the space occupied by the system. It's a good suggestion to let users choose the installation item. Thank you.

**Comment by aidlearning** [comment]
habe reduce the size to 800M after installed!
