### ISSUE TITLE
install llvmlite(a python module) failed

### ISSUE THREAD

**Issue by CSUTailorWu** [aidlearning/AidLearning-FrameWork#28]
I want to install numba to test my python project, but when I `pip2 install numba`,the `llvmlite ` rely is failed,how can I support it

**Comment by aidlearning** [comment]
I now try it and later will reported for u

**Comment by aidlearning** [comment]
1.
cat /etc/apt/sources.list deb http://llvm.org/apt/jessie/ llvm-toolchain-jessie main deb-src http://llvm.org/apt/jessie/ llvm-toolchain-jessie main deb http://llvm.org/apt/jessie/ llvm-toolchain-jessie-3.6 main deb-src http://llvm.org/apt/jessie/ llvm-toolchain-jessie-3.6 main
2.
gpg --keyserver pgpkeys.mit.edu --recv-key 15CF4D18AF4F7421
gpg -a --export 15CF4D18AF4F7421 | apt-key add -
3.
apt-get update
apt-get install cython python-llvm build-essential libedit-dev
apt-get install llvm-3.6 llvm-3.6-dev llvm-dev
4.
LLVM_CONFIG=/usr/lib/llvm-3.6/bin/llvm-config pip install llvmlite
LLVM_CONFIG=/usr/lib/llvm-3.6/bin/llvm-config pip install numba

**Comment by CSUTailorWu** [comment]
Thankyou for your help,I now try it

**Comment by CSUTailorWu** [comment]
Thankyou for your help,I now try it

**Comment by CSUTailorWu** [comment]
> cat /etc/apt/sources.list deb http://llvm.org/apt/jessie/ llvm-toolchain-jessie main deb-src http://llvm.org/apt/jessie/ llvm-toolchain-jessie main deb http://llvm.org/apt/jessie/ llvm- toolchain-jessie-3.6 main deb-src http://llvm.org/apt/jessie/ llvm-toolchain-jessie-3.6 main 
sorry,I try cat /etc/apt/sources.list, not like your list. so, `vim` alter the `sources.list` like your list. I ask a question: the list format importance?
> 2. 
> gpg --keyserver pgpkeys .mit.edu --recv-key 15CF4D18AF4F7421 
Than, I try this bash, `recevice failed: No data`
> gpg -a --export 15CF4D18AF4F7421 | apt-key add - 
> 3. 
> apt-get update 
> apt-get install cython python-llvm build-essential libedit-dev 
> apt-get install llvm-3.6 llvm-3.6-dev llvm-dev 
> 4. 
> LLVM_CONFIG = / usr / lib / llvm -3.6 / bin / llvm-config pip install llvmlite
> LLVM_CONFIG = / usr / lib / llvm-3.6 / bin / llvm-config pip install numba

**Comment by aidlearning** [comment]
1.the format of sources.list is not import. you can vim it .
2.gpg --keyserver pgp.mit.edu --recv-key 15CF4D18AF4F7421 may you can connect pkg.mit.edu or not pkgkeys.mit.edu

**Comment by CSUTailorWu** [comment]
root@localhost:/home# gpg -a --export 15CF4D18AF4F7421 | apt-key add -
gpg: [don't know]: invalid packet (ctb=00)
gpg: keydb_search failed: Invalid packet
gpg: [don't know]: invalid packet (ctb=00)
gpg: keydb_get_keyblock failed: Value not found
gpg: [don't know]: invalid packet (ctb=00)
gpg: /tmp/apt-key-gpghome.pxLsYZipkC/pubring.gpg: copy to '/tmp/apt-key-gpghome.pxLsYZipkC/pubring.gpg.tmp' failed: Invalid packet
gpg: error writing keyring '/tmp/apt-key-gpghome.pxLsYZipkC/pubring.gpg': Invalid packet
gpg: [don't know]: invalid packet (ctb=00)
gpg: error reading '-': Invalid packet
gpg: import from '-' failed: Invalid packet

**Comment by aidlearning** [comment]
can u run 3 and 4 directly?
if u cannot find llvm-3.6 you can try apt-get install llvm llvm-dev

**Comment by CSUTailorWu** [comment]
I think sources.list set error, I copy your list in `vim sources list`
`root@localhost:/home# cat /etc/apt/sources.list deb http://llvm.org/apt/jessie/ llvm-toolchain-jessie main
deb-src http://llvm.org/apt/jessie/ llvm-toolchain-jessie main
deb http://llvm.org/apt/jessie/ llvm-toolchain-jessie-3.6 main
deb-src http://llvm.org/apt/jessie/ llvm-toolchain-jessie-3.6 main`

`root@localhost:/home# gpg --keyserver pgpkeys.mit.edu --recv-key 15CF4D18AF4F7421
gpg: key 15CF4D18AF4F7421: 1 signature not checked due to a missing key
gpg: key 15CF4D18AF4F7421: "Sylvestre Ledru - Debian LLVM packages <sylvestre@debian.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1`

`root@localhost:/home# gpg -a --export 15CF4D18AF4F7421 | apt-key add -
gpg: [don't know]: invalid packet (ctb=00)
gpg: keydb_search failed: Invalid packet
gpg: [don't know]: invalid packet (ctb=00)
gpg: keydb_get_keyblock failed: Value not found
gpg: [don't know]: invalid packet (ctb=00)
gpg: /tmp/apt-key-gpghome.pxLsYZipkC/pubring.gpg: copy to '/tmp/apt-key-gpghome.pxLsYZipkC/pubring.gpg.tmp' failed: Invalid packet
gpg: error writing keyring '/tmp/apt-key-gpghome.pxLsYZipkC/pubring.gpg': Invalid packet
gpg: [don't know]: invalid packet (ctb=00)
gpg: error reading '-': Invalid packet
gpg: import from '-' failed: Invalid packet`

**Comment by aidlearning** [comment]
ok,i try it again....maybe you are right
