### ISSUE TITLE
how can i run GUI app such as vscode on AidLearning-FrameWork?I try to run mousepad,but it return this error "cannot open display   Trace/breakpoint trap" 

### ISSUE THREAD

**Issue by Ripo-za** [aidlearning/AidLearning-FrameWork#29]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aidlearning** [comment]
sorry,I don't know the mousepad, the Aidlearning Support the  GUI.  If you're new to development, follow the documentation, and it will work. But there is no guarantee that it supports any downloaded source code that can run on it.
