### ISSUE TITLE
Ver0.73 will be released!

### ISSUE THREAD

**Issue by aidlearning** [aidlearning/AidLearning-FrameWork#30]
Ver0.73 will be released in the next few days!
It will greatly improve the convenience and stability of the system.
touch-and-drag programming experience will be imported  into UI development！

**Comment by aidlearning** [comment]
now released!<br> What's new:
<br>
1.  Fixed the bug that <b>apt update</b> failed (ps:The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD62925553 NO_PUBKEY 7638D0442B90D010 NO_PUBKEY EF0F382A7B6500)
2.  AiCode has major updates:

- The interface and menu were redesigned to fix the bug of floating menu occlusion code.
- New code auto-prompting function, if you input the initial letters of variables, functions and keywords, the system will <b>automatically complete</b> , which can greatly improve efficiency.
	<p align=center>
          <img src="autocode.gif" width=300px />
	</p>
- New ui Design Interface (Wizard), now ui design does not require you to write ui code , you can use <b>touch and drag </b>Components to generate ui codes. We have built-in a large number of UI development components，the system will automatically generate ui code, you only need to focus on the core processing code.

3.  Redesign the example codes and use the new ui Design method.

4.  Because of the importing of touch and drag programming, the development code now adopts the method of separating the ui interface from the personal core processing code. The ui interface code is generated by the system, and the core processing code system also generates the port, you can focus on the part you really want to deal with.

5.  Fixed the problem of relying on a small amount of network traffic. Now even if your mobile phone is in flight mode, it can run the system.

6.  Update other bugs that affect stability

**Comment by hackaidroid** [comment]
i install the new version, apt update is working . Wizard by drag and touch  Components to design the ui is really cool.how to reduce the size of the system ? it need 20 minutes to finished the install....

**Comment by aidlearning** [comment]
Because there are many frameworks and dependency packages built-in, the whole installation process is relatively long. But with the advent of 5G, maybe these are not problems. I'll try to give you the option to install it, but it's a complicated job that may be implemented in the next version.
