### ISSUE TITLE
on ver 0.75,what is optional to install?

### ISSUE THREAD

**Issue by ailittlebrain** [aidlearning/AidLearning-FrameWork#32]
V0.75 is a very good version because it takes up less disk space. What does it simplify? Or what is optional to install?

**Comment by aidlearning** [comment]
v0.75 is a mini version ,already build in python2/python3 surpport.and also built in OpenCV for python2 and 3. but the AI framework like caffe/mxnet/tensorflow/torch not built in.but when you finished the install .you can install them by hit the icon of upgrade on the destop.
![WechatIMG2](https://user-images.githubusercontent.com/49776013/61633527-e01a5b00-acc1-11e9-9efd-87cbd33bf82f.png)
