### ISSUE TITLE
the program  sshd is not installed

### ISSUE THREAD

**Issue by 2151330** [aidlearning/AidLearning-FrameWork#33]
![77a4b6c601ebf1d26ed192e09020593](https://user-images.githubusercontent.com/41284417/61860077-edbb2500-aefb-11e9-8a5c-f4c2eb39ce47.jpg)
When I finished the installation, I encountered this problem, I don't know how to solve it, can you help me?

**Comment by 2151330** [comment]
When i run pkg install openssh, this problem happened？ 
![Screenshot_20190725_165251_com aidlux](https://user-images.githubusercontent.com/41284417/61860606-d3ce1200-aefc-11e9-8865-1630185df2e6.jpg)

**Comment by aidlearning** [comment]
There are two possibilities for this problem. One is that your storage space is insufficient, resulting in incomplete decompression of dependent packages. Another case is that the network is interrupted when the dependent package is downloaded, which results in the incomplete download of the dependent package. The solution is to delete the app and then download and install it again.

**Comment by 2151330** [comment]
Many thanks！
