### ISSUE TITLE
Is it possible to install AidLearning-Framework on a linux desktop?

### ISSUE THREAD

**Issue by hallher** [aidlearning/AidLearning-FrameWork#34]

**Comment by aidlearning** [comment]
Yes, you can install AidLearning on a linux desktop ,If your Linux system is an arm64 architecture, such as nano pi, strawberry pi, etc.

**Comment by hallher** [comment]
Thanks. Great work!

**Comment by BradleyWang123** [comment]
How can I install AidLearning on  my jetson nano pi？ I can't run the apk in my linux system.

**Comment by BradleyWang123** [comment]
@qidiso How can I install AidLearning on my jetson nano pi？ I can't run the apk in my linux system.
