### ISSUE TITLE
Is there a users guide for using the wizard. Having a real struggle trying to use it. Thanks

### ISSUE THREAD

**Issue by hallher** [aidlearning/AidLearning-FrameWork#35]

**Comment by aidlearning** [comment]
I will give a guide document for the wizard recently....sorry I am busy today

**Comment by hallher** [comment]
No problem. Thanks so much

**Comment by aidlearning** [comment]
pls read 
1、https://github.com/aidlearning/AidLearning-FrameWork/blob/master/gui_cvs/README.md
2、https://github.com/aidlearning/AidLearning-FrameWork/blob/master/gui_wizard/README.md

**Comment by hallher** [comment]
Thank you so much. This will be a great help. I look forward to learning
more.
