### ISSUE TITLE
my android cpu:ARMv7 Processor rev 4,How can I slove ”not executable: 64-bit ELF file” when install

### ISSUE THREAD

**Issue by caoyouxiu** [aidlearning/AidLearning-FrameWork#36]
my android cpu:ARMv7 Processor rev 4,How can I slove ”not executable: 64-bit ELF file” when install

**Comment by qidiso** [comment]
AidLearning Only support the arm64/aarch Processor now, maybe your android is 32-bit cpu(arm32),so now is not support.will be supported later
