### ISSUE TITLE
有操作的视频说明吗？

### ISSUE THREAD

**Issue by airaining** [aidlearning/AidLearning-FrameWork#37]
非常棒的工具！我已经跑通了几个例子，有视频操作教程吗？

**Comment by qidiso** [comment]
https://www.youtube.com/watch?v=bkvNXgCi3_c&list=LLg4MJJ0IWeJ4kqAc1pAOcGg&index=2&t=0s

**Comment by aidlearning** [comment]
will upload more video's of introduce aid learning....
