### ISSUE TITLE
can you share the sources of facerecognize.so ?

### ISSUE THREAD

**Issue by angleseeu** [aidlearning/AidLearning-FrameWork#38]
i run the facencnn examples ,it's fast and perfect! but i want to run the other models using the method,but need to modified the so, can u help me?

**Comment by qidiso** [comment]
pls give the emails...

**Comment by TuringZhai** [comment]
1. can you share the sources of facerecognize.so ?  mail:jfzhai2016@icloud.com
2. I'm going to move the face recognition part to arm Linux, not based on 'turmux'

**Comment by lucaslu1987** [comment]
can you also share the sources of facerecognize.so to me? email: lucaslu1987@hotmail.com
thanks.
