### ISSUE TITLE
convert facencnn model to ncnn, not supported yet

### ISSUE THREAD

**Issue by onexuan** [aidlearning/AidLearning-FrameWork#4]
BlockGrad not supported yet!
one_hot not supported yet!
977 depth=85742
off_value=0.0
on_value=1.0
pick not supported yet!
axis=1
where not supported yet!

**Comment by aidlearning** [comment]
Is ncnn the latest version you use? No problem when I switch.

**Comment by onexuan** [comment]
> Is ncnn the latest version you use? No problem when I switch.

Do you have a custom layer?

**Comment by onexuan** [comment]
> > Is ncnn the latest version you use? No problem when I switch.
> 
> Do you have custom layers?

**Comment by aidlearning** [comment]
no,i don't all custom layers

**Comment by onexuan** [comment]
Could you upload your ncnn model for testing.
