### ISSUE TITLE
startup script

### ISSUE THREAD

**Issue by kaishijeng** [aidlearning/AidLearning-FrameWork#44]
Is there a way which a script will execute when I launch AidLearning app?
The usecase is to have a python task running on a background (no need to have a console screen) inside AidLearning and communicate with Android application via TCP.

Thanks,

**Comment by aidlearning** [comment]
you can edit the .bashrc using the following command:
`vi ~/.bashrc `

**Comment by kaishijeng** [comment]
Will aidlearning start to run when android tablet powers up?
My application is to run some python code in the background when the system boots.

Thanks,

**Comment by aidlearning** [comment]
I need some test .... and give your wanted
