### ISSUE TITLE
can you share the sources of facerecognize.so ?

### ISSUE THREAD

**Issue by xiaonaoer** [aidlearning/AidLearning-FrameWork#48]
https://github.com/aidlearning/AidLearning-FrameWork/issues/38

**Comment by aidlearning** [comment]
I need to get rid of the business stuff and send it back to you.

**Comment by TuringZhai** [comment]
ok，thanks！
like this url： https://github.com/flycat0101/ncnn-face-recognition/blob/master/src/facerecognition.cpp ？，but it is Not all

**Comment by aidlearning** [comment]
yes, he is my friends

**Comment by TuringZhai** [comment]
that's great

**Comment by TuringZhai** [comment]
It doesn't have this method 'facerecog.getfacepose()'.
If you have time, please send me the email:jfzhai2016@icloud.com
thanks!
