### ISSUE TITLE
It doesn't have this method 'facerecog.getfacepose()'.

### ISSUE THREAD

**Issue by xiaonaoer** [aidlearning/AidLearning-FrameWork#49]
It doesn't have this method 'facerecog.getfacepose()'.
If you have time, please send me the email:jfzhai2016@icloud.com
thanks!

_Originally posted by @TuringZhai in https://github.com/aidlearning/AidLearning-FrameWork/issues/48#issuecomment-530298435_

**Comment by TuringZhai** [comment]
I want to filter out the side face or the down face
