### ISSUE TITLE
can't install on my android tablet

### ISSUE THREAD

**Issue by kaishijeng** [aidlearning/AidLearning-FrameWork#5]
I download aidlux-0505.apk to my android pad and install it, but failed to install.
Android tablet just says App not installed.
Any idea?

**Comment by aidlearning** [comment]
Can you share your pad configuration? For example, Android 6.0 or 7.0？now ,the app support android >=6.0 and aarch64 .

**Comment by kaishijeng** [comment]
I used adb install aidlux-0505.apk and it works now

**Comment by aidlearning** [comment]
ok

**Comment by kaishijeng** [comment]
I just registered it, but not receive an activation email yet. Can you
approve it

Thanks,

**Comment by aidlearning** [comment]
i check it

**Comment by aidlearning** [comment]
your account is activated by hand.sorry for the mail system not stable!

**Comment by kaishijeng** [comment]
Thanks,

**Comment by kaishijeng** [comment]
How do I customize user interface, like adding an button and different layout of GUI?
I don't see it in your python example

Thanks

**Comment by aidlearning** [comment]
good question!
Of course! you can customize your Gui use the AidLearning. you can cd /home/facencnn and reference:
    line 35~43 :
        _msgType,msgName=cvs.getMsg()
        if msgName!='' and msgType=='add_person':
            ret=facerecog.add_person(msgName, img.shape[0], img.shape[1], image_char)
            if ret==0:
                print 'you add_person is success!'
                cvs.setMsg_status(1)
            else :
                print 'you add_person is failed!'
                cvs.setMsg_status(-1)_
this is to process button to register a face to recognize. how to customize the button ?
pls reference the templates dir 下的index.html file

**Comment by kaishijeng** [comment]
3 questions:
1) I noticed wifi has a lot of traffic when landmark app is running. Does application send data or picture to internet?
2) Is sshd enabled? It will be useful to have a connection between my PC and my android tablet. So I can do editing and upload my own model
3) Which version of opencv is installed in your system?

Thanks,

**Comment by aidlearning** [comment]
no send  any data to internet. but the gui is part build of the web .so you have the traffic. sshd already surpported.i will show the help how to do.opencv is 3

**Comment by kaishijeng** [comment]
I am not able to use ssh to access my android tablet with your SW installed. Do I need to run a command to start sshd?

**Comment by aidlearning** [comment]
no,sshd already started. you just to copy the .ssh/id_rsa.pub (int the pc) to the .ssh/authorized_keys

**Comment by kaishijeng** [comment]
Is there userid and password for ssh?
what is port number for ssh?

Thanks,

**Comment by aidlearning** [comment]
for example :in my pc : ssh u0_a201@192.168.1.6 -p8022

**Comment by aidlearning** [comment]
your pc is mac or linux?if it is true ,pls in the terminal run:ssh-keygen to generate the id_rsa.pub file

**Comment by kaishijeng** [comment]
LInux.  Unfortunately, it still asks me for password after I install id_ras.pub to autorizex_keys on your system.
I used termux before and I can do ssh to termux from my linux

Thanks,

**Comment by aidlearning** [comment]
# ssh(use the pc to connect to Aidlearning and control it using the pc's terminal)
Just open the url:mobilephone'sip:8910/upload in the pc to upload ssh's file. for example:http://192.168.1.6:8910/upload

i upgrade the ssh setting method!!!

**Comment by kaishijeng** [comment]
Do I need to update aidlearning instead of :using http://192.168.1.6:8910/upload?
w

**Comment by aidlearning** [comment]
you need download apk to install.and then open  url:mobilephone'sip:8910/upload
upload your id_ras and idras.pub. last yiu can use ssh u0_a201@192.168.1.6 -p8022 to connect

**Comment by kaishijeng** [comment]
where to download apk and which version of apk to download?

Thanks,

**Comment by aidlearning** [comment]
https://github.com/aidlearning/AidLearning-FrameWork/blob/master/aidlux0510.apk

**Comment by kaishijeng** [comment]
I upload id_ras and id_ras.pub using http://192.168.20.30:8910/upload
However, when I  ssh  u0_a201@192.168.20.30 -p8022, I got the following
error:

Permission denied (publickey,keyboard-interactive).

**Comment by qidiso** [comment]
you input correct passqord?


 
---Original---

**Comment by kaishijeng** [comment]
I got it work now. The issue is due to termux is active.
One more question:
when I run landmark app and register my name, I don't see my name showing
up in the upper video window.
How do I use landmark app?


Thanks,

**Comment by qidiso** [comment]
you should run face recognize app if you want reg your face and show the recog name


 
---Original---

**Comment by kaishijeng** [comment]
Where is face recognition app?
I only see terminal, landmark and pose icon on the GUI.

**Comment by aidlearning** [comment]
you can tap the bottom icon like app store.it will show more examples

**Comment by kaishijeng** [comment]
opencv2 in the system is 2.4.9.1, not 3 which you mentioned before. 
I want to use dnn module in the opencv 3.5 or 3.6.

>>> import cv2
>>> cv2.__version__
'2.4.9.1'

Thanks,

**Comment by aidlearning** [comment]
you can see this: https://github.com/aidlearning/AidLearning-FrameWork/issues/6#issuecomment-491295054
use:  apt install opencv3-dev来安装opencv3
