### ISSUE TITLE
Installing failed in huawei p30 pro emui 10

### ISSUE THREAD

**Issue by he426100** [aidlearning/AidLearning-FrameWork#51]
exec("/data/data/com.aidlux/files/usr/bin/login"): Permission denied

[Process completed (code 1) - press Enter]

**Comment by aidlearning** [comment]
i will try it but i have mo huawei p30 pro.. .may be you install not completely...,you can uninstall it anfld retry it again

**Comment by dobefore** [comment]
maybe you could try uninstalling the app,and try installing the app

**Comment by he426100** [comment]
I've tried many times, but it's useless. maybe the reason for android 10?

**Comment by aidlearning** [comment]
You are right! i will try it for android 10 ... i need update my rom

**Comment by aidlearning** [comment]
new version 0.85 already support android 10,pls try it....
