### ISSUE TITLE
upgrade error still exists,though version 9-4

### ISSUE THREAD

**Issue by dobefore** [aidlearning/AidLearning-FrameWork#52]
when i run apt upgrade,error emerges:is there anyone who can help me?iknow i have posted the same issue once ,but there's no one respoding to me.I am addicted to this software.thanks anyway.
`root@localhost:/home# apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  autopoint dbus gettext gettext-base icu-devtools libavcodec-dev libavcodec57 libavformat-dev libavformat57 libavutil-dev libavutil55 libcups2 libdbus-1-3 libexpat1 libexpat1-dev libgd3
  libglib2.0-0 libglib2.0-bin libglib2.0-data libglib2.0-dev libicu-dev libicu57 libldap-2.4-2 libldap-common libmariadbclient18 libpng-dev libpng-tools libpng16-16 libssl-dev libssl-doc
  libssl1.0.2 libssl1.1 libswresample-dev libswresample2 libswscale-dev libswscale4 libxslt1.1 linux-libc-dev openssh-client openssl patch tzdata unzip vim vim-common vim-runtime xxd
47 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
4 not fully installed or removed.
Need to get 0 B/64.4 MB of archives.
After this operation, 131 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
/bin/sh: 1: /usr/sbin/dpkg-preconfigure: not found
Setting up libudev1:arm64 (232-25+deb9u12) ...
dpkg: warning: files list file for package 'python3-cryptography' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3.5' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3-dbus' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3-cffi-backend' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3-keyring' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3-crypto' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'libpython3.5:arm64' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'libssl-dev:arm64' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'libpython3.5-stdlib:arm64' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3-idna' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3-xdg' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3-keyrings.alt' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3-wheel' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3-gi' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'libpython3.5-dev:arm64' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3.5-minimal' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3-pyasn1' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3-pip' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'libssl-doc' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3-setuptools' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3.5-dev' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3-secretstorage' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'libpython3.5-minimal:arm64' missing; assuming package has no files currently installed
(Reading database ... 63996 files and directories currently installed.)
Preparing to unpack .../00-unzip_6.0-21+deb9u2_arm64.deb ...
Unpacking unzip (6.0-21+deb9u2) over (6.0-21+deb9u1) ...
/var/lib/dpkg/info/unzip.postrm: 4: /var/lib/dpkg/info/unzip.postrm: update-mime: not found
dpkg: warning: subprocess old post-removal script returned error exit status 127
dpkg: trying script from the new package instead ...
/var/lib/dpkg/tmp.ci/postrm: 4: /var/lib/dpkg/tmp.ci/postrm: update-mime: not found
dpkg: error processing archive /tmp/apt-dpkg-install-e86RU7/00-unzip_6.0-21+deb9u2_arm64.deb (--unpack):
 subprocess new post-removal script returned error exit status 127
/var/lib/dpkg/tmp.ci/postrm: 4: /var/lib/dpkg/tmp.ci/postrm: update-mime: not found
dpkg: error while cleaning up:
 subprocess new post-removal script returned error exit status 127
Preparing to unpack .../01-tzdata_2019b-0+deb9u1_all.deb ...
Unpacking tzdata (2019b-0+deb9u1) over (2019a-0+deb9u1) ...
Preparing to unpack .../02-libssl1.0.2_1.0.2s-1~deb9u1_arm64.deb ...
Unpacking libssl1.0.2:arm64 (1.0.2s-1~deb9u1) over (1.0.2r-1~deb9u1) ...
Preparing to unpack .../03-libssl-doc_1.1.0k-1~deb9u1_all.deb ...
Unpacking libssl-doc (1.1.0k-1~deb9u1) over (1.1.0j-1~deb9u1) ...
Preparing to unpack .../04-libssl-dev_1.1.0k-1~deb9u1_arm64.deb ...
Unpacking libssl-dev:arm64 (1.1.0k-1~deb9u1) over (1.1.0j-1~deb9u1) ...
Preparing to unpack .../05-libssl1.1_1.1.0k-1~deb9u1_arm64.deb ...
Unpacking libssl1.1:arm64 (1.1.0k-1~deb9u1) over (1.1.0j-1~deb9u1) ...
Preparing to unpack .../06-vim_2%3a8.0.0197-4+deb9u3_arm64.deb ...
Unpacking vim (2:8.0.0197-4+deb9u3) over (2:8.0.0197-4+deb9u1) ...
Preparing to unpack .../07-vim-runtime_2%3a8.0.0197-4+deb9u3_all.deb ...
Unpacking vim-runtime (2:8.0.0197-4+deb9u3) over (2:8.0.0197-4+deb9u1) ...
Preparing to unpack .../08-xxd_2%3a8.0.0197-4+deb9u3_arm64.deb ...
Unpacking xxd (2:8.0.0197-4+deb9u3) over (2:8.0.0197-4+deb9u1) ...
Preparing to unpack .../09-vim-common_2%3a8.0.0197-4+deb9u3_all.deb ...
Unpacking vim-common (2:8.0.0197-4+deb9u3) over (2:8.0.0197-4+deb9u1) ...
Preparing to unpack .../10-dbus_1.10.28-0+deb9u1_arm64.deb ...
Unpacking dbus (1.10.28-0+deb9u1) over (1.10.26-0+deb9u1) ...
Preparing to unpack .../11-libdbus-1-3_1.10.28-0+deb9u1_arm64.deb ...
Unpacking libdbus-1-3:arm64 (1.10.28-0+deb9u1) over (1.10.26-0+deb9u1) ...
Preparing to unpack .../12-libexpat1-dev_2.2.0-2+deb9u2_arm64.deb ...
Unpacking libexpat1-dev:arm64 (2.2.0-2+deb9u2) over (2.2.0-2+deb9u1) ...
Preparing to unpack .../13-libexpat1_2.2.0-2+deb9u2_arm64.deb ...
Unpacking libexpat1:arm64 (2.2.0-2+deb9u2) over (2.2.0-2+deb9u1) ...
Preparing to unpack .../14-gettext-base_0.19.8.1-2+deb9u1_arm64.deb ...
Unpacking gettext-base (0.19.8.1-2+deb9u1) over (0.19.8.1-2) ...
Preparing to unpack .../15-libldap-common_2.4.44+dfsg-5+deb9u3_all.deb ...
Unpacking libldap-common (2.4.44+dfsg-5+deb9u3) over (2.4.44+dfsg-5+deb9u2) ...
Preparing to unpack .../16-libldap-2.4-2_2.4.44+dfsg-5+deb9u3_arm64.deb ...
Unpacking libldap-2.4-2:arm64 (2.4.44+dfsg-5+deb9u3) over (2.4.44+dfsg-5+deb9u2) ...
Preparing to unpack .../17-openssh-client_1%3a7.4p1-10+deb9u7_arm64.deb ...
Unpacking openssh-client (1:7.4p1-10+deb9u7) over (1:7.4p1-10+deb9u6) ...
Preparing to unpack .../18-libglib2.0-data_2.50.3-2+deb9u1_all.deb ...
Unpacking libglib2.0-data (2.50.3-2+deb9u1) over (2.50.3-2) ...
Preparing to unpack .../19-libglib2.0-dev_2.50.3-2+deb9u1_arm64.deb ...
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 32, in <module>
    from debpython import files as dpf
ModuleNotFoundError: No module named 'debpython'
dpkg: warning: subprocess old pre-removal script returned error exit status 1
dpkg: trying script from the new package instead ...
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 32, in <module>
    from debpython import files as dpf
ModuleNotFoundError: No module named 'debpython'
dpkg: error processing archive /tmp/apt-dpkg-install-e86RU7/19-libglib2.0-dev_2.50.3-2+deb9u1_arm64.deb (--unpack):
 subprocess new pre-removal script returned error exit status 1
Traceback (most recent call last):
  File "/usr/bin/py3compile", line 34, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
ModuleNotFoundError: No module named 'debpython'
dpkg: error while cleaning up:
 subprocess installed post-installation script returned error exit status 1
Preparing to unpack .../20-libglib2.0-bin_2.50.3-2+deb9u1_arm64.deb ...
Unpacking libglib2.0-bin (2.50.3-2+deb9u1) over (2.50.3-2) ...
Preparing to unpack .../21-libglib2.0-0_2.50.3-2+deb9u1_arm64.deb ...
Unpacking libglib2.0-0:arm64 (2.50.3-2+deb9u1) over (2.50.3-2) ...
Preparing to unpack .../22-gettext_0.19.8.1-2+deb9u1_arm64.deb ...
Unpacking gettext (0.19.8.1-2+deb9u1) over (0.19.8.1-2) ...
Preparing to unpack .../23-autopoint_0.19.8.1-2+deb9u1_all.deb ...
Unpacking autopoint (0.19.8.1-2+deb9u1) over (0.19.8.1-2) ...
Preparing to unpack .../24-libicu-dev_57.1-6+deb9u3_arm64.deb ...
Unpacking libicu-dev (57.1-6+deb9u3) over (57.1-6+deb9u2) ...
Preparing to unpack .../25-icu-devtools_57.1-6+deb9u3_arm64.deb ...
Unpacking icu-devtools (57.1-6+deb9u3) over (57.1-6+deb9u2) ...
Preparing to unpack .../26-libicu57_57.1-6+deb9u3_arm64.deb ...
Unpacking libicu57:arm64 (57.1-6+deb9u3) over (57.1-6+deb9u2) ...
Preparing to unpack .../27-libavformat-dev_7%3a3.2.14-1~deb9u1_arm64.deb ...
Unpacking libavformat-dev:arm64 (7:3.2.14-1~deb9u1) over (7:3.2.12-1~deb9u1) ...
Preparing to unpack .../28-libavcodec-dev_7%3a3.2.14-1~deb9u1_arm64.deb ...
Unpacking libavcodec-dev:arm64 (7:3.2.14-1~deb9u1) over (7:3.2.12-1~deb9u1) ...
Preparing to unpack .../29-libswresample-dev_7%3a3.2.14-1~deb9u1_arm64.deb ...
Unpacking libswresample-dev:arm64 (7:3.2.14-1~deb9u1) over (7:3.2.12-1~deb9u1) ...
Preparing to unpack .../30-libswresample2_7%3a3.2.14-1~deb9u1_arm64.deb ...
Unpacking libswresample2:arm64 (7:3.2.14-1~deb9u1) over (7:3.2.12-1~deb9u1) ...
Preparing to unpack .../31-libswscale-dev_7%3a3.2.14-1~deb9u1_arm64.deb ...
Unpacking libswscale-dev:arm64 (7:3.2.14-1~deb9u1) over (7:3.2.12-1~deb9u1) ...
Preparing to unpack .../32-libswscale4_7%3a3.2.14-1~deb9u1_arm64.deb ...
Unpacking libswscale4:arm64 (7:3.2.14-1~deb9u1) over (7:3.2.12-1~deb9u1) ...
Preparing to unpack .../33-libavutil-dev_7%3a3.2.14-1~deb9u1_arm64.deb ...
Unpacking libavutil-dev:arm64 (7:3.2.14-1~deb9u1) over (7:3.2.12-1~deb9u1) ...
Preparing to unpack .../34-libavutil55_7%3a3.2.14-1~deb9u1_arm64.deb ...
Unpacking libavutil55:arm64 (7:3.2.14-1~deb9u1) over (7:3.2.12-1~deb9u1) ...
Preparing to unpack .../35-libavcodec57_7%3a3.2.14-1~deb9u1_arm64.deb ...
Unpacking libavcodec57:arm64 (7:3.2.14-1~deb9u1) over (7:3.2.12-1~deb9u1) ...
Preparing to unpack .../36-libavformat57_7%3a3.2.14-1~deb9u1_arm64.deb ...
Unpacking libavformat57:arm64 (7:3.2.14-1~deb9u1) over (7:3.2.12-1~deb9u1) ...
Preparing to unpack .../37-libcups2_2.2.1-8+deb9u4_arm64.deb ...
Unpacking libcups2:arm64 (2.2.1-8+deb9u4) over (2.2.1-8+deb9u3) ...
Preparing to unpack .../38-libpng-tools_1.6.28-1+deb9u1_arm64.deb ...
Unpacking libpng-tools (1.6.28-1+deb9u1) over (1.6.28-1) ...
Preparing to unpack .../39-libpng-dev_1.6.28-1+deb9u1_arm64.deb ...
Unpacking libpng-dev:arm64 (1.6.28-1+deb9u1) over (1.6.28-1) ...
Preparing to unpack .../40-libpng16-16_1.6.28-1+deb9u1_arm64.deb ...
Unpacking libpng16-16:arm64 (1.6.28-1+deb9u1) over (1.6.28-1) ...
Preparing to unpack .../41-libgd3_2.2.4-2+deb9u5_arm64.deb ...
Unpacking libgd3:arm64 (2.2.4-2+deb9u5) over (2.2.4-2+deb9u4) ...
Preparing to unpack .../42-libmariadbclient18_10.1.41-0+deb9u1_arm64.deb ...
Unpacking libmariadbclient18:arm64 (10.1.41-0+deb9u1) over (10.1.38-0+deb9u1) ...
Preparing to unpack .../43-libxslt1.1_1.1.29-2.1+deb9u1_arm64.deb ...
Unpacking libxslt1.1:arm64 (1.1.29-2.1+deb9u1) over (1.1.29-2.1) ...
Preparing to unpack .../44-linux-libc-dev_4.9.189-3_arm64.deb ...
Unpacking linux-libc-dev:arm64 (4.9.189-3) over (4.9.168-1) ...
Preparing to unpack .../45-openssl_1.1.0k-1~deb9u1_arm64.deb ...
Unpacking openssl (1.1.0k-1~deb9u1) over (1.1.0j-1~deb9u1) ...
Preparing to unpack .../46-patch_2.7.5-1+deb9u2_arm64.deb ...
Unpacking patch (2.7.5-1+deb9u2) over (2.7.5-1+deb9u1) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-e86RU7/00-unzip_6.0-21+deb9u2_arm64.deb
 /tmp/apt-dpkg-install-e86RU7/19-libglib2.0-dev_2.50.3-2+deb9u1_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by aidlearning** [comment]
maybe you need 
`apt update`
first

**Comment by dobefore** [comment]
Thanks for replying!I ve tried it as you suggested，you see its the same，can you figure out what‘s problems with my operation?
android 6  HUAWEI P8
`root@localhost:/home# apt update
Ign:1 http://deb.debian.org/debian stretch InRelease           
Hit:2 http://deb.debian.org/debian stretch Release
Reading package lists... Done
Building dependency tree       
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.`


and I run `apt upgrade `

```
Do you want to continue? [Y/n] y
/bin/sh: 1: /usr/sbin/dpkg-preconfigure: not found
dpkg: warning: files list file for package 'python3-cryptography' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3.5' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3-dbus' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3-cffi-backend' missing; assuming package has no files currently installed
dpkg: error while cleaning up:
 subprocess installed post-installation script returned error exit status 1
Preparing to unpack .../unzip_6.0-21+deb9u2_arm64.deb ...
Unpacking unzip (6.0-21+deb9u2) over (6.0-21+deb9u1) ...
/var/lib/dpkg/info/unzip.postrm: 4: /var/lib/dpkg/info/unzip.postrm: update-mime: not found
dpkg: warning: subprocess old post-removal script returned error exit status 127
dpkg: trying script from the new package instead ...
/var/lib/dpkg/tmp.ci/postrm: 4: /var/lib/dpkg/tmp.ci/postrm: update-mime: not found
dpkg: error processing archive /var/cache/apt/archives/unzip_6.0-21+deb9u2_arm64.deb (--unpack):
 subprocess new post-removal script returned error exit status 127
/var/lib/dpkg/tmp.ci/postrm: 4: /var/lib/dpkg/tmp.ci/postrm: update-mime: not found
dpkg: error while cleaning up:
 subprocess new post-removal script returned error exit status 127
Errors were encountered while processing:
 /var/cache/apt/archives/libglib2.0-dev_2.50.3-2+deb9u1_arm64.deb
 /var/cache/apt/archives/unzip_6.0-21+deb9u2_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by dobefore** [comment]
> maybe you need
> `apt update`
> first

Thanks for replying!I ve tried it as you suggested，you see its the same，can you figure out what‘s problems with my operation?
android 6 HUAWEI P8
`root@localhost:/home# apt update Ign:1 http://deb.debian.org/debian stretch InRelease Hit:2 http://deb.debian.org/debian stretch Release Reading package lists... Done Building dependency tree Reading state information... Done 2 packages can be upgraded. Run 'apt list --upgradable' to see them.`

and I run `apt upgrade`

```
Do you want to continue? [Y/n] y
/bin/sh: 1: /usr/sbin/dpkg-preconfigure: not found
dpkg: warning: files list file for package 'python3-cryptography' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3.5' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3-dbus' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python3-cffi-backend' missing; assuming package has no files currently installed
dpkg: error while cleaning up:
 subprocess installed post-installation script returned error exit status 1
Preparing to unpack .../unzip_6.0-21+deb9u2_arm64.deb ...
Unpacking unzip (6.0-21+deb9u2) over (6.0-21+deb9u1) ...
/var/lib/dpkg/info/unzip.postrm: 4: /var/lib/dpkg/info/unzip.postrm: update-mime: not found
dpkg: warning: subprocess old post-removal script returned error exit status 127
dpkg: trying script from the new package instead ...
/var/lib/dpkg/tmp.ci/postrm: 4: /var/lib/dpkg/tmp.ci/postrm: update-mime: not found
dpkg: error processing archive /var/cache/apt/archives/unzip_6.0-21+deb9u2_arm64.deb (--unpack):
 subprocess new post-removal script returned error exit status 127
/var/lib/dpkg/tmp.ci/postrm: 4: /var/lib/dpkg/tmp.ci/postrm: update-mime: not found
dpkg: error while cleaning up:
 subprocess new post-removal script returned error exit status 127
Errors were encountered while processing:
 /var/cache/apt/archives/libglib2.0-dev_2.50.3-2+deb9u1_arm64.deb
 /var/cache/apt/archives/unzip_6.0-21+deb9u2_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by aidlearning** [comment]
Hello, in order to make the dependency packages as small as possible, we deleted something unrelated to deep learning, so I think your operation is correct. But why do you use the upgrade command? Which package do you want to install? You can use apt install XXX to finished.

**Comment by ottoskyer** [comment]
这问题一直都有，那怕先update也没用。希望尽快解决。
