### ISSUE TITLE
Is there any possibility thansplanting opencv-contrib-python?

### ISSUE THREAD

**Issue by dobefore** [aidlearning/AidLearning-FrameWork#53]
the fact is I want to install and use airtest in this app,yet it needs support of opencv-contrib-python .thanks a lot.

**Comment by aidlearning** [comment]
You can recompile opencv with contrib using OpenCV sources. Because the package becomes larger after adding contrib, there is no built-in contrib... different versions may be released later to support this requirement.

**Comment by dobefore** [comment]
> You can recompile opencv with contrib using OpenCV sources. Because the package becomes larger after adding contrib, there is no built-in contrib... different versions may be released later to support this requirement.

If I recompile,is it necessary to uninstall the current opencv?
if so,how could do it?by `pip uninstall opencv` does it work?

**Comment by aidlearning** [comment]
you can use the following command to try:
`pip3 uninstall opencv`
`pip3 install opencv-contrib-python` or
`pip2 uninstall opencv`
`pip2 install opencv-contrib-python`

**Comment by aidlearning** [comment]
using pip3 install opencv-contrib-python....it have the packet for the arm...so you must recompile it...you can see the url:
https://github.com/tdicola/pi_python_opencv_contrib

**Comment by dobefore** [comment]
its very kind of you，thank you ！I‘ll try
