### ISSUE TITLE
cannot see installing progress

### ISSUE THREAD

**Issue by dyseo** [aidlearning/AidLearning-FrameWork#55]
First download and installing dependencies i can't see the progress
<img src="https://i.ibb.co/grsm52K/Screenshot-20190922-045104.jpg" href="#">

that is bug or what?
overall and thanks before, this greate project

**Comment by dobefore** [comment]
cant' you see the installation progress is processing at the bottom of the screen,it may take a couple of minutes to be ready

**Comment by dyseo** [comment]
> cant' you see the installation progress is processing at the bottom of the screen,it may take a couple of minutes to be ready

how about weird cursor at IDE, i have confused about this
i have some [Gif](https://hostquick.onlineconverter.com/file/20017afa54497dbf7a0cc4b9bffbcc0d3a/download) for this

**Comment by qfmail** [comment]
that is right,because of the screen size,may cause this ,but it is ok.



---Original---

**Comment by aidlearning** [comment]
you may chang the theme ,so the default theme is cobalt....it is test ok for cursor...but the other theme I don't test ....may cause the problem...thank you for tell me.

-- how about weird cursor at IDE， i have confused about this

**Comment by dyseo** [comment]
> you may chang the theme ,so the default theme is cobalt....it is test ok for cursor...but the other theme I don't test ....may cause the problem...thank you for tell me.
> 
> -- how about weird cursor at IDE， i have confused about this

doesn't work for my device, I'm using VIVO V5S btw

**Comment by aidlearning** [comment]
You can  install a new input method to try it....

**Comment by dyseo** [comment]
> You can install a new input method to try it....

same, i have download trying google input, and hacker keyboard and try change all of them that doesn't work cursor still weird

**Comment by aidlearning** [comment]
I will find a vivo phone to test it ......it's confused

**Comment by dyseo** [comment]
> I will find a vivo phone to test it ......it's confused

ahh really? i'm so glad about that cuz i never see IDE like that on phone, that is best IDE for editing code
