### ISSUE TITLE
Can it support read and write from external storage(ie:sdcard) ?

### ISSUE THREAD

**Issue by dobefore** [aidlearning/AidLearning-FrameWork#56]
looking forward to early reply!

**Comment by aidlearning** [comment]
external storage sdcard is in the dir /sdcard, so you  can do:
 `cd /sdcard;ls`

**Comment by dobefore** [comment]
I mean a removable SD card ,there an extendible interface that allow me to extend my phone storage

**Comment by aidlearning** [comment]
I don't have a removable sdcard mobile phone. I don't know its directory structure, so I can't map it to a directory, sorry.

**Comment by aidlearning** [comment]
have solved the question in the version version >0.85 ,mounted the removable SD card  dir on the /storage
