### ISSUE TITLE
“Segmentation fault” when running commands like “apt update”, “dpkg -i test.deb”

### ISSUE THREAD

**Issue by yusanshi** [aidlearning/AidLearning-FrameWork#57]
Android Device: Xiaomi 6
Android Version: Android 9 (LineageOS 16.0-20191002-NIGHTLY-sagit)
AidLearning Version: 0.76 (aidlux-09-04.apk)

“Segmentation fault” when trying installing some packages.
Believing this may have something to do with Magisk (To root my device I installed Magisk 19.3 after flashing LineageOS ROM), I uninstalled it but that doesn’t work. 

Thx a lot!

```
root@localhost:~# dpkg -i wtf.deb
Segmentation fault
root@localhost:~# apt update
Segmentation fault
root@localhost:~# apt moo
                 (__)
                 (oo)
           /------\/
          / |    ||
         *  /\---/\
            ~~   ~~
..."Have you mooed today?"...
root@localhost:~# dpkg --help
Usage: dpkg [<option> ...] <command>

<omitted>
```

**Comment by yusanshi** [comment]
I’d like to add that when I first met such problem, I think my device is a little “dirty” to some degree since I have dirty flashed ROMs a lot, and this may be the reason. So I did a entirely reset (wiped Cache, System, Vendor, Data, Internal Storage partitions in TWRP, then flashed ROM and Magisk).
But not works.

**Comment by dobefore** [comment]
are you trying to change sources？change to home sources and try again？

**Comment by yusanshi** [comment]
> are you trying to change sources？change to home sources and try again？

@dobefore Sorry to bother but would you please explain it in more detail? What should I do to change to home source? Thx a lot!

**Comment by dobefore** [comment]
What a coincidence! several days ago,you've helped me how to recompille the opencv,thank you .
I mean apt sources,run following commands:
`vi /etc/apt/sources.list`
comment the existing codes，with #
and add the UTSC source:
```
deb http://mirrors.ustc.edu.cn/debian stable main contrib non-free
# deb-src http://mirrors.ustc.edu.cn/debian stable main contrib non-free
deb http://mirrors.ustc.edu.cn/debian stable-updates main contrib non-free
# deb-src http://mirrors.ustc.edu.cn/debian stable-updates main contrib non-free

# deb http://mirrors.ustc.edu.cn/debian stable-proposed-updates main contrib non-free
# deb-src http://mirrors.ustc.edu.cn/debian stable-proposed-updates main contrib non-free
```

**Comment by dobefore** [comment]
maybe you shuld better run this command `apt install apt-transport-https` before the above command,sorry for that,I 've almost forgot

**Comment by yusanshi** [comment]
@dobefore  Well, after changing `sources.list`, such problem still exists. And after `apt install apt-transport-https`, I input `y`, then `Segmentation fault` again.

Thx anyway!

In fact, What I really want is to use OpenCV and ADB (use ADB to control phone itself, without a PC). I have gived up AidLearning for such annoying `Segmentation fault`, as well as building OpenCV from source in Termux. My final solution is to modify my code to use Pillow instead of OpenCV since installing Pillow in Termux is quite easy.

**Comment by aidlearning** [comment]
I think the main reason is that the directory structure of root's mobile phone has changed, so the ADB related so library has been changed, which eventually leads to Segmentation fault. I didn't reply to your question because I didn't have a root phone, so I'm sorry.
