### ISSUE TITLE
How can I solve "Permission denied" after intalling the lastest version on andriod10?

### ISSUE THREAD

**Issue by LuSany** [aidlearning/AidLearning-FrameWork#59]
I installed the lastest version of 0.77 on HUAWEI P30 and the emui10 were update before the installation of aidlearning. when finishing installing all of the dependencies ,there is a message shows as below:

("/data/data/com.aidlux/files/usr/bin/login"): Permission denied

how can I deal with this err?

**Comment by aidlearning** [comment]
I haven't tested the Huawei P30 mobile phone. The Huawei P30 system should be the latest Android 10. I will test it as soon as possible and give some suggestions. Android 10 may have a new security policy, I will test it as soon as possible，think your test...

**Comment by aidlearning** [comment]
I make the app using compileSdkVersion 29 (android) to build. it maybe work for android 10(p30 's android version)...you can try it 
[app-release.apk.zip](https://github.com/aidlearning/AidLearning-FrameWork/files/3747849/app-release.apk.zip)

**Comment by LuSany** [comment]
I installed the new apk file and the "permission denied" err stil exist.

**Comment by aidlearning** [comment]
sorry for this, can u provide the screenshot of the error and  android version info?

**Comment by LuSany** [comment]
screenshot of err：
![Screenshot_20191021_115636_com aidlux](https://user-images.githubusercontent.com/36779890/67177067-63e9fd80-f3ff-11e9-8b8d-2efd6f373dc0.jpg)

version of andriod:
![Screenshot_20191021_115747](https://user-images.githubusercontent.com/36779890/67177079-75cba080-f3ff-11e9-953f-fa39eb402ca9.jpg)

**Comment by aidlearning** [comment]
thank u.！we will fix it as soon as possible

**Comment by LuSany** [comment]
thanks for your efforts.

**Comment by LonelyLinear** [comment]
Is this problem solved? I have the same situation. my phone is Google pixel 2 and Android 10

**Comment by LuSany** [comment]
Not yet,I guess it will be fixed at next version

**Comment by aidlearning** [comment]
[fuck10.apk.zip](https://github.com/aidlearning/AidLearning-FrameWork/files/3802462/fuck10.apk.zip)
this now support android 10,welcome testing.....

**Comment by LonelyLinear** [comment]
> [fuck10.apk.zip](https://github.com/aidlearning/AidLearning-FrameWork/files/3802462/fuck10.apk.zip)
> this now support android 10,welcome testing.....

Very grateful (btw I like the apk name, LOL)

**Comment by LonelyLinear** [comment]
> [fuck10.apk.zip](https://github.com/aidlearning/AidLearning-FrameWork/files/3802462/fuck10.apk.zip)
> this now support android 10,welcome testing.....

When I try to upgrade pip, it shows that:
root@localhost:/home# pip install --upgrade pip
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
proot warning: signal 11 received from process 0
$                                                        $                                                        $

**Comment by LonelyLinear** [comment]
And gnome can't be opened

**Comment by aidlearning** [comment]
pip2 install --upgrade pip or pip3 install --upgrade pip. gnome is still developing...

**Comment by LonelyLinear** [comment]
> pip2 install --upgrade pip or pip3 install --upgrade pip. gnome is still developing...

Thanks! btw what does “app store” do？Do u have any instructions for it？ Thx

**Comment by aidlearning** [comment]
app store means more examples of deep learning can downloading ............you can also visit by http://code.aidlearning.net:3000/explore/repos in your explore.

**Comment by LuSany** [comment]
new version has been released
