### ISSUE TITLE
Stuck at Installing

### ISSUE THREAD

**Issue by zuhairabs** [aidlearning/AidLearning-FrameWork#61]
![Screenshot_2019-11-12-06-56-39-038_com aidlux](https://user-images.githubusercontent.com/41848715/68634066-32ee7b80-051a-11ea-9813-96b22f542c9c.jpg)
App is stuck on Installing 59% for more than 20 mins.

And nothing Working.

**Comment by aidlearning** [comment]
During the installation process, you need to download about 10 dependent packages, the first five are relatively small, the sixth to the tenth are relatively large, and one package is more than 100m, so the later progress will be slower. The dependency package is on Alibaba cloud, so the network speed is limited by Alibaba cloud. If the download is not complete, aidlux will not function properly.

**Comment by JustBornForHer** [comment]
Same problem here.....
Mine stuck at 10%

**Comment by zuhairabs** [comment]
Wait Lots of Dependencies are Installed, so wait it takes significant amout of Time.
