### ISSUE TITLE
Not Opening anything

### ISSUE THREAD

**Issue by zuhairabs** [aidlearning/AidLearning-FrameWork#62]
![Screenshot_2019-11-12-07-02-08-769_com aidlux](https://user-images.githubusercontent.com/41848715/68634142-7b0d9e00-051a-11ea-99aa-43473a0da7c8.jpg)
When I click on any Icon it goes blank

**Comment by aidlearning** [comment]
During the installation process, you need to download about 10 dependent packages, the first five are relatively small, the sixth to the tenth are relatively large, and one package is more than 100m, so the later progress will be slower. The dependency package is on Alibaba cloud, so the network speed is limited by Alibaba cloud. If the download is not complete, aidlux will not function properly. It is recommended that you remove it and reinstall it....

**Comment by zuhairabs** [comment]
Can I get list of dependent packages. So I can try downloading manually

**Comment by aidlearning** [comment]
Since the installation of DEB files has order and interdependence, the installation dependency is controlled by script, so it is difficult to install manually

**Comment by aidlearning** [comment]
the arm32 not supported!
