### ISSUE TITLE
Failed to run pose example.

### ISSUE THREAD

**Issue by hello-yaowq** [aidlearning/AidLearning-FrameWork#64]
Two face apps on the desktop can work well in my K20pro(MIUI11, Android10), but  i failed to run the pose app, the last log shows
run py2 log=> python:can't open file 'aid.log':[Errno 2] No such file or directory
run py3 log=> webcam_demo.py error:: unrecoginized arguments:50000

How can i solve these problems,thx!

**Comment by aidlearning** [comment]
I try it ....find the bug too. I will fix it .....one other way you can open the terminal and run in command:
```
cd /home/mutipose/
python3 web_demo.py
```
you can try it....thank u give the bug info...

**Comment by aidlearning** [comment]
new version 0.86 have fixed the bug...
