### ISSUE TITLE
Remi and Editor update

### ISSUE THREAD

**Issue by dddomodossola** [aidlearning/AidLearning-FrameWork#66]
Hello,

I'm here to inform you about important Remi https://github.com/dddomodossola/remi updates. These changes comprises an API change: the Widget class is no more a container, and so it was removed the method *append* from it. The class Container have to be used in replacement to Widget.
Additionally, the Editor has different new improvements:
1. It now can load external additional widgets: there are available some OpenCv, Siemens and EPICS widgets. Maybe you can consider to create your own widgets set.
2. The events can now be connected to existing widget methods. It previously create a custom listener method. This allows widgets interaction during editing. In example, if I put an OpencvVideo widget, I can connect the event *on_new_image* to the OpencvThreshold.on_new_image_listener, and so, when a new frame occurs it automatically gets transferred to the Threshold, without writing code.

There are also different bug fixes.

Regards,
Davide

**Comment by aidlearning** [comment]
it is very cool.....thank u very much! I will try it ....
