### ISSUE TITLE
How can I get back to the editor after click the show log button

### ISSUE THREAD

**Issue by zeromniverse** [aidlearning/AidLearning-FrameWork#67]
Hello,
    When I use the AidCode to write the python project,I can run py3 but if I want to see the result such as print function I have to click the show log and it works normally then I can't get back to the code only I can do is to close the IDE and open it again.Is there any button to back the code editor?

Thanks

**Comment by aidlearning** [comment]
I will add one repack menu,thank your testing...

**Comment by aidlearning** [comment]
version 0.80 is add the menu of return log to src

**Comment by stevetech1963** [comment]
//`joli= 42 v obligation building TMobile pickpocket unobtrusive continue puzzle luckily implying`

**Comment by aidlearning** [comment]
new version have solved this
