### ISSUE TITLE
how to run jupyter on it?

### ISSUE THREAD

**Issue by yuanzhi-zhu** [aidlearning/AidLearning-FrameWork#68]
I use pip3 to install jupyter and it seems the jupyter is well installed. However, when I type jupyter notebook and enter, it reported wrong: No module named pysqlite2 and No module named _sqlite3. And then I failed to install these two modules.

How can I install jupyter on aidlearning properly? Massive thanks in advance.

**Comment by aidlearning** [comment]
on the ver0.80 the Jupyter is well installed , you can hit the icon Jupyter of the desktop to launch it . when launched it need password:admin. you can visit it on the pc use the url:
http://+mobile's ip +:8888

**Comment by aidlearning** [comment]
note: Jupyter is already launched .so you don't need to key: jupyter notebook.
<img width="1280" alt="jupyter" src="https://user-images.githubusercontent.com/49776013/71329834-1a836f00-2564-11ea-96cf-246868e5f9f5.png">
<img width="1280" alt="screen" src="https://user-images.githubusercontent.com/49776013/71329836-1b1c0580-2564-11ea-9bea-33d2d68515e5.png">

**Comment by yuanzhi-zhu** [comment]
@aidlearning Jupyter works smoothly on the new version of aidlearning, thanks.
This project is great!!!
