### ISSUE TITLE
如何设置os终端仅可以在本地(127.0.0.1)访问

### ISSUE THREAD

**Issue by 1343890272** [aidlearning/AidLearning-FrameWork#70]
我可以在局域网任意设备访问它，感觉非常的不安全
或者可以给它加个密码

**Comment by aidlearning** [comment]
We will add an authentication module, which requires a password to access the LAN. A new version will be released in the near future

**Comment by aidlearning** [comment]
since ver0.84, aid have the authentication module buildin, so u can try it by command:`passwd demo` to setting password.
