### ISSUE TITLE
无法运行nmap

### ISSUE THREAD

**Issue by 1343890272** [aidlearning/AidLearning-FrameWork#71]
在我使用nmap扫描时出现错误
nmap: netutil.cc:3285: int route_dst_netlink(const sockaddr_storage*, route_nfo*, const char*, const sockaddr_storage*): Assertion `p != NULL' failed.
Aborted

**Comment by aidlearning** [comment]
How do you install nmap? Is the apt install command used？I will try it...

**Comment by ssmellon** [comment]
分布式架构-Redis高并发分布式锁-0217
链接：https://pan.baidu.com/s/1PjVIcBrtys24IA83bIcjjw&nbsp;
提取码：65tu
全民
多线程文字预习资料：
链接：https://pan.baidu.com/s/1xePkWsj4HrDALzVK2jVFhg&nbsp;
提取码：k1ia
多线程视频预习资料：
链接：https://pan.baidu.com/s/1kpG0ztocSCDvSEnZQqSGEw&nbsp;
提取码：ae7n




---原始邮件---
发件人: "bill"<notifications@github.com&gt;
发送时间: 2020年2月18日(周二) 凌晨4:02
收件人: "aidlearning/AidLearning-FrameWork"<AidLearning-FrameWork@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [aidlearning/AidLearning-FrameWork] 无法运行nmap (#71)



Closed #71.
