### ISSUE TITLE
请问可以支持预装最新版的wps office for linux arm吗，希望在大屏安卓平板上能有办公能力

### ISSUE THREAD

**Issue by zihaoxingstudy1** [aidlearning/AidLearning-FrameWork#74]
请问可以支持预装最新版的wps office for linux arm吗，希望在大屏安卓能有办公能力

![深度截图_选择区域_20200118220535](https://user-images.githubusercontent.com/58220227/72664976-ce322e80-3a3e-11ea-99a2-8993f8ec8852.png)

**Comment by aidlearning** [comment]
you can try it using the command:
dpkg -i wps.deb

**Comment by ichit** [comment]
This is just a request: hi i was wondering if you guys can add more kernels to jupyter, like octave, java script and R kernels. This will be highly appriciated as it can help some of is to keep working on our task when we are on the move. thanks kind regards

**Comment by aidlearning** [comment]
ok, we try on my best!
