### ISSUE TITLE
I cannot run examples with python3 and the IDE showed that no python3 installed. 

### ISSUE THREAD

**Issue by LuSany** [aidlearning/AidLearning-FrameWork#76]
after installing V0.81, I cannot run examples with python3 and the IDE showed that no python3 installed. there's no errs or warnings during the installation.

**Comment by aidlearning** [comment]
I think it may be the problem of installation. It should be that the dependency package of Python 3 is not fully installed. There may be a bug in this. Thank you for providing this bug. We will test it more.

**Comment by aidlearning** [comment]
already fixed，pls downloads at url:[http://16787372.s21d-16.faiusrd.com/0/ABUIABBKGAAgouHs8QUoztWgCA?f=v0.811.apk&v=1580937378](url)
