### ISSUE TITLE
Aidlearing can't be a SSH server？

### ISSUE THREAD

**Issue by starhou** [aidlearning/AidLearning-FrameWork#78]
About the method "http://192.168.1.6:8910/upload",  it only works when two devices are in the same LAN. I tried to send `id_rsa.pub` to my Aidlearning, but I can't use my PC (by ssh) to connect my Aidlearing on my phone after that. It works well using Aidlearing on my phone to connect my PC. I thought it may be I have no "openssh-server" on my Aidlearing.

When  I tried to install "openssh-server" through `apt-get install openssh-server`, an error `dpkg: error processing package libpam-systemd:arm64 (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 openssh-server
 systemd
 libpam-systemd:arm64
E: Sub-process /usr/bin/dpkg returned an error code (1)` occur。

If I could connect my Aidlearing use SSH, I don't need to ensure that both devices are on the same LAN every time. It will be fantastic !

**Comment by sunyi1018** [comment]
I think `OpenSSH` has already built-in Aidlearning...
Why don't you try to use the commands like `ssh u0_a311@192.168.1.6 -p8022` that is provided in the ReadMe?

**Comment by sunyi1018** [comment]
You can use `whoami` command, then replace `u0_a311` with the output.

**Comment by aidlearning** [comment]
can u give me a screenshot of connect....?

**Comment by starhou** [comment]
Surely, I have just tried with 'ssh root@myip -p 8022'.&nbsp; It doesn't work and throw "connection timed out" . Perhaps I can't connect with root user?



---Original---

**Comment by aidlearning** [comment]
aid' builtin sshserver is in the low-level of the aidlux：so u can do the following command:
`exit;whoami`

**Comment by sunyi1018** [comment]
> Surely, I have just tried with 'ssh root@myip -p 8022'.&nbsp; It doesn't work and throw "connection timed out" . Perhaps I can't connect with root user?
> […](#)
> ---Original--- From: "sunyi1018"<notifications@github.com&gt; Date: Thu, Feb 6, 2020 11:55 AM To: "aidlearning/AidLearning-FrameWork"<AidLearning-FrameWork@noreply.github.com&gt;; Cc: "Star Hou"<1029588176@qq.com&gt;;"Author"<author@noreply.github.com&gt;; Subject: Re: [aidlearning/AidLearning-FrameWork] Aidlearing can't be a SSH server？ (#78) You can use whoami command, then replace u0_a311 with the output. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Hmmm...What kind of LAN are you using, personal or public?  Maybe the LAN is blocked.

**Comment by starhou** [comment]
I used whoami and got "root" . The connection response is as follows,

![evidence](https://user-images.githubusercontent.com/46232202/73906445-e7135e80-48dd-11ea-9593-be4913d5db51.JPG)

My client is Alibaba Cloud Server and server is Aidlearning

**Comment by starhou** [comment]
On PC, I could connect with Aidlearning by `http://192.168.1.6:8000` . It's OK!
I'd like to know how can I show a '*.PNG' with Aidlearing. Is there an example?

**Comment by aidlearning** [comment]
you only need is open the document icon on the desktop ,choose the path of the png, open it....
