### ISSUE TITLE
upgrade error

### ISSUE THREAD

**Issue by shiqunld** [aidlearning/AidLearning-FrameWork#80]
aid version:0.81

dpkg: error processing archive /var/cache/apt/archives/perl_5.24.1-3+deb9u6_arm64.deb (--unpack):
 unable to stat './usr/bin/c2ph' (which I was about to install): Operation not permitted
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Preparing to unpack .../perl-base_5.24.1-3+deb9u6_arm64.deb ...
Unpacking perl-base (5.24.1-3+deb9u6) over (5.24.1-3+deb9u5) ...
dpkg: error processing archive /var/cache/apt/archives/perl-base_5.24.1-3+deb9u6_arm64.deb (--unpack):
 unable to stat './usr/bin/perl' (which I was about to install): Operation not permitted

**Comment by aidlearning** [comment]
New Version will solve the question, thank u!
