### ISSUE TITLE
类似vnc连接之后的鼠标指针将屏幕作为触控板

### ISSUE THREAD

**Issue by lancerXXXX** [aidlearning/AidLearning-FrameWork#86]
![image](https://user-images.githubusercontent.com/42160297/75434285-45d37180-598c-11ea-8941-9edddce006a5.png)

这个桌面并不很适合移动端,或者说触屏, 在iphone 还是3G 那时候,乔布斯规定 按钮的大小至少要44x44, 以带来更好的用户体验,这个应用是在手机端使用桌面端的应用,一些按钮过小, 触屏但仍然是桌面端的操作方式,
这也是win10平板模式被吐槽的很大原因,
我们的确是想要在移动端使用桌面端的应用, 
在使用vnc连接我的ubuntu时, 这个模拟的鼠标给我带来的了不亚于windows触控板的体验,
当然你可以说我夸大其词, 但是的确给我的使用感受带来了很大的提升,因为他几乎是将平板的屏幕作为了一个触摸板,

**Comment by aidlearning** [comment]
我们下一步会支持鼠标的，谢谢支持
