### ISSUE TITLE
命令行更新一些包，安装python3所需的一些库都有问题

### ISSUE THREAD

**Issue by wishyer** [aidlearning/AidLearning-FrameWork#87]
运行py的时候提示缺库文件，命令行又安装不上.
另外，vscode中运行某些py，图形结果能显示出来吗？

**Comment by aidlearning** [comment]
python3已经内置了，如果要显示图形界面，请在py文件中包含语句:
`from cvs import *`
具体参照说明文件

**Comment by aidlearning** [comment]
如果在vscode里运行自带例子，请现在vsc的命令行里cd到py的那个目录，在运行py文件，因为例程中有加载模型文件
