### ISSUE TITLE
可以支持下坚果手机TNT模式吗

### ISSUE THREAD

**Issue by strongduanmu** [aidlearning/AidLearning-FrameWork#88]
![image](https://user-images.githubusercontent.com/10829171/75504758-52031180-5a14-11ea-968b-6bfc44d6348b.png)
坚果手机TNT模式，类似于PC电脑桌面，希望能支持下屏幕自由拉伸缩放。

**Comment by aidlearning** [comment]
我们可以尝试，但是会不会显得屏幕更小了？

**Comment by strongduanmu** [comment]
> 我们可以尝试，但是会不会显得屏幕更小了？

希望可以尝试下🙏，您说的显得屏幕更小具体是指？界面上的字符展示先得小？

**Comment by aidlearning** [comment]
界面上给aid显示的空间就变小了哦

**Comment by SpinningK** [comment]
浏览器输入localhost:8000就有了
