### ISSUE TITLE
linux commands Permission denied.

### ISSUE THREAD

**Issue by xingdouchen** [aidlearning/AidLearning-FrameWork#89]
root@localhost:~# top

top: failed tty set: Permission denied
root@localhost:~#
root@localhost:~# vmstat
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
/proc/stat: Permission denied
root@localhost:~#

I also use linux commands and find it is permission denied, such as top/vmstat ...
any solutions?

**Comment by aidlearning** [comment]
Because of the android have no root permission, so vmstat cannot run on aid. next version will find  
a way to slove the question ....

**Comment by xingdouchen** [comment]
> Because of the android have no root permission, so vmstat cannot run on aid. next version will find
> a way to slove the question ....

what's the time of next version?Thanks~

**Comment by aidlearning** [comment]
have the test version of 0.83, pls reference the url:
https://www.yuque.com/glg1kx/aidlearning/cee0vu

**Comment by xingdouchen** [comment]
> have the test version of 0.83, pls reference the url:
> https://www.yuque.com/glg1kx/aidlearning/cee0vu

Great,太赞了！
是所有需要linux root权限的命令，都可以用了吗？
Are there all linux commands which needs root can be used now？
