### ISSUE TITLE
建议默认增加python lxml库

### ISSUE THREAD

**Issue by xingdouchen** [aidlearning/AidLearning-FrameWork#90]
发现中文也可以，那就用中文吧：
lxml库在做python爬虫时候比较常用，希望默认加上去下，自己安装找方法比较麻烦；

附带昨天找到的方法：（先编译所需依赖）
#编译所需依赖
apt-get install -y python-pip python-dev python3-pip python3-dev libxml2-dev libxslt-dev zlib1g-dev
# pip3 for python3.x
pip3 install lxml
# pip for python2.x
pip install lxml

**Comment by aidlearning** [comment]
OK , thank u!
