### ISSUE TITLE
After a while it is constantly stuck on the Loading screen

### ISSUE THREAD

**Issue by adamhill** [aidlearning/AidLearning-FrameWork#93]
After using AID for a while (like just running the examples) the Desktop will reboot to the animated Loading screen and get stuck there. Continuously playing the animations. The only way to fix this is closing the AID desktop and relaunching the app.

This is a very new device – Note 10+, 1TB of storage. Nothing else is running on the phone (fresh reboot)

**Comment by aidlearning** [comment]
thank u for privide the bug.the aid start more services on launching...we will fix it and release a new version fix the bugs by choosing services by your need to start...

**Comment by aidlearning** [comment]
have solved in the v0.86 version
