### ISSUE TITLE
VS Code Does Not Obey Language Settings

### ISSUE THREAD

**Issue by adamhill** [aidlearning/AidLearning-FrameWork#94]
If you go into Settings and set it to 'English' VS Code still runs as if the language is Chinese.

**Comment by aidlearning** [comment]
Yes，but you can modify it on ~/.e.sh

**Comment by maksxfaktor** [comment]
please read more

**Comment by aidlearning** [comment]
sorry，I made a mistake. It should be a file of ～ /. Bashrc. You should comment out the sentence lang = zh cn.utf-8

**Comment by maksxfaktor** [comment]
thanks a lot

**Comment by maksxfaktor** [comment]
unsubscribe

**Comment by maksxfaktor** [comment]
many thanks, changes successfully

**Comment by aidlearning** [comment]
u r welcome!

**Comment by aidlearning** [comment]
VS Code Language Settings
