### ISSUE TITLE
Can't Install successfully On Android 6

### ISSUE THREAD

**Issue by I-love-study** [aidlearning/AidLearning-FrameWork#98]
Phone: Meilan5s(魅蓝5s)
System:Flyme 6.3.0.3A Base on Android 6.0
Android安全补丁日期:2018.2.5
APK:0.84b2

![S00408-094520](https://user-images.githubusercontent.com/39652142/78855163-bb376500-7a55-11ea-9fe5-57c43d3bffb5.jpg)

在初次启动下载完依赖包出现如上画面
之后重新打开就是如下画面

![S00409-11335647](https://user-images.githubusercontent.com/39652142/78855329-2a14be00-7a56-11ea-8d9b-8d9728e213ae.jpg)

无法进入Aid desktop

**Comment by aidlearning** [comment]
we release a version for fix the bug of android 6 , pls try:
[app-0.84-b3-for-android6.apk.zip](https://github.com/aidlearning/AidLearning-FrameWork/files/4454130/app-0.84-b3-for-android6.apk.zip)

**Comment by I-love-study** [comment]
Same problem again in new version(0.86b2)
